<a href="https://colab.research.google.com/github/luciaphmaestria/labo2025v/blob/main/src/ensembles/594_TareaHogar_05_1semilla_0.5Undersampling_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea para el Hogar 05

Esta Tarea para el Hogar 05 se entrega el final de la cuarta clase
<br> se espera de usted que intente avanzar con los desafios propuestos y que los traiga terminados para la Clase 05 que será el miercoles 03 de septiembre

##  1. Overfitting the Public Leaderboard

Leer  https://medium.com/hmif-itb/overfitting-the-leaderboard-da25172ac62e
( 8 minutos )

## 2. Hiperparámetros del LightGBM

Los objetivos de esta tarea son:


*   Aumentar la rentabilidad de la campaña de marketing de retención proactiva de clientes.
*   Generar un mejor modelo optimizando sus hiperparámetros
*   Conceptual : investigar los mas relevantes hiperparámetros de LightGBM
*   Familiarizarse con la Bayesian Optimization, sus largos tiempos de corrida y opciones para reducirlos
*   Familiarizarse con el uso de máquinas virtuales de Google Colab
*   Ver un pipeline completo de optimización de hiperparámetros y puesta en producción

LightGBM cuenta con mas de 60 hiperparámetros, siendo posible utilizar 40 al mismo tiempo, aunque no razonable.
<br> La documentación oficial de los hiperparámetros de LightGBM es  https://lightgbm.readthedocs.io/en/latest/Parameters.html#core-parameters

Se lo alerta sobre que una Optimizacion Bayesiana lleva varias horas de corrida, y usted deberá correr VARIAS optimizaciones para descubrir cuales parámetros conviene optimizar.
<br> A pesar que la próxima clase es recien en viernes 01 de agosto, inicie la tarea con tiempo, aprenda a planificar estratégicamente sus corridas como un@ científ@  de datos.

Es necesario investigar cuales son los hiperparámetros de LightGBM que vale la pena optimizar en una Bayesian Optimization, ya que los realmente utiles son apenas un reducido subconjunto.
<br>Usted deberá investigar cuales son los hiperparámetros mas relevantes de LightGBM, su primer alternativa es preguntándole a su amigo con capacidades especiales ChatGPT o sus endogámicos familiares Claude, DeepSeek, Gemini, Grok, etc
<br> La segunda alternativa es la propia documentación de LightGBM  https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html

Adicionalmente podra buscar información como la que proveen esta diminuta muestra aleatoria de artículos ligeros:
* https://machinelearningmastery.com/light-gradient-boosted-machine-lightgbm-ensemble/
*  https://medium.com/@sarahzouinina/a-deep-dive-into-lightgbm-how-to-choose-and-tune-parameters-7c584945842e
*  https://www.kaggle.com/code/somang1418/tuning-hyperparameters-under-10-minutes-lgbm
*  https://towardsdatascience.com/beginners-guide-to-the-must-know-lightgbm-hyperparameters-a0005a812702/


<br>  La muestra anterior se brinda a modo de ejemplo, usted deberá buscar muuuuchas  fuentes adicionales de información
<br> Tenga presente que LightGBM es el estado del arte en modelado predictivo para datasets estructurado, que son el 90% del trabajo del 95% de los Data Scientists en Argentina.

El desafío de esta tarea es:
* Qué hiperparparámetros conviene optimizar?  Las recomendaciones de los artículos ligeros es siempre sensata?  Sus autores realmente hicieron experimentos o son siemplemente escritores de entretenimiento carente de base científica?
* Elegidos los hiperparámetros, cual es el  <desde, hasta> que se debe utilizar en la Bayesian Optimization ?
* Realmente vale la pena optimizar 10 o 16 hiperparámetros al mismo tiempo ?  No resulta contraproducente una búsqueda en un espacio de tal alta dimensionalidad ?

#### 2.1  Seteo del ambiente en Google Colab

Esta parte se debe correr con el runtime en Python3
<br>Ir al menu, Runtime -> Change Runtime Type -> Runtime type ->  **Python 3**

Conectar la virtual machine donde esta corriendo Google Colab con el  Google Drive, para poder tener persistencia de archivos

In [1]:
# primero establecer el Runtime de Python 3
from google.colab import drive
drive.mount('/content/.drive')

Drive already mounted at /content/.drive; to attempt to forcibly remount, call drive.mount("/content/.drive", force_remount=True).

Para correr la siguiente celda es fundamental en Arranque en Frio haber copiado el archivo kaggle.json al Google Drive, en la carpeta indicada en el instructivo

<br>los siguientes comando estan en shell script de Linux
*   Crear las carpetas en el Google Drive
*   "instalar" el archivo kaggle.json desde el Google Drive a la virtual machine para que pueda ser utilizado por la libreria  kaggle de Python
*   Bajar el  **dataset_pequeno**  al  Google Drive  y tambien al disco local de la virtual machine que esta corriendo Google Colab

In [2]:
%%shell

mkdir -p "/content/.drive/My Drive/labo1"
mkdir -p "/content/buckets"
ln -s "/content/.drive/My Drive/labo1" /content/buckets/b1

mkdir -p ~/.kaggle
cp /content/buckets/b1/kaggle/kaggle.json  ~/.kaggle
chmod 600 ~/.kaggle/kaggle.json


mkdir -p /content/buckets/b1/exp
mkdir -p /content/buckets/b1/datasets
mkdir -p /content/datasets



archivo_origen="https://storage.googleapis.com/open-courses/austral2025-af91/dataset_pequeno.csv"
archivo_destino="/content/datasets/dataset_pequeno.csv"
archivo_destino_bucket="/content/buckets/b1/datasets/dataset_pequeno.csv"

if ! test -f $archivo_destino_bucket; then
  wget  $archivo_origen  -O $archivo_destino_bucket
fi


if ! test -f $archivo_destino; then
  cp  $archivo_destino_bucket  $archivo_destino
fi

ln: failed to create symbolic link '/content/buckets/b1/labo1': File exists

### 2.2 Optimizacion Hiperparámetros

Esta parte se debe correr con el runtime en lenguaje R Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

### 2.2.1 Inicio

limpio el ambiente de R

In [1]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Tue Nov 04 03:15:29 AM 2025"

In [2]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  660381 35.3 1454477    77.7 1454477  77.7
Vcells 1226627  9.4 8388608    64.0 1975128  15.1

### 2.2.2 Carga de Librerias

In [3]:
# cargo las librerias que necesito
require("data.table")
require("parallel")

if( !require("primes") ) install.packages("primes")
require("primes")

if( !require("utils") ) install.packages("utils")
require("utils")

if( !require("rlist") ) install.packages("rlist")
require("rlist")

if( !require("yaml")) install.packages("yaml")
require("yaml")

if( !require("lightgbm") ) install.packages("lightgbm")
require("lightgbm")

if( !require("DiceKriging") ) install.packages("DiceKriging")
require("DiceKriging")

if( !require("mlrMBO") ) install.packages("mlrMBO")
require("mlrMBO")

Loading required package: data.table

Loading required package: parallel

Loading required package: primes

Loading required package: rlist

Loading required package: yaml

Loading required package: lightgbm

Loading required package: DiceKriging

Loading required package: mlrMBO

Loading required package: mlr

Loading required package: ParamHelpers

Loading required package: smoof

Loading required package: checkmate


Attaching package: ‘checkmate’


The following object is masked from ‘package:DiceKriging’:

    checkNames

### 2.2.3 Definicion de Parametros

aqui debe cargar SU semilla primigenia
<br>recuerde cambiar el numero de experimento en cada corrida nueva

In [4]:
PARAM <- list()
PARAM$experimento <- 5943
PARAM$semilla_primigenia <- 120539
PARAM$semilla_primigenia2 <- 230431

In [ ]:
PARAM$kaggle$competencia <- "labo-i-2025-virtual-analista-sr"
PARAM$kaggle$cortes <- seq(10000, 12000, by= 500)

In [5]:
# un undersampling de 0.1  toma solo el 10% de los CONTINUA
# undersampling de 1.0  implica tomar TODOS los datos

PARAM$trainingstrategy$undersampling <- 0.5                          # Lu. Le pongo 0.5 porque sigue siendo muy desbalanceada la clase

In [6]:
# Parametros LightGBM

PARAM$hyperparametertuning$xval_folds <- 5

# parametros fijos del LightGBM que se pisaran con la parte variable de la BO
PARAM$lgbm$param_fijos <-  list(
  boosting= "gbdt", # puede ir  dart  , ni pruebe random_forest
  objective= "binary",
  metric= "auc",
  first_metric_only= FALSE,
  boost_from_average= TRUE,
  feature_pre_filter= FALSE,
  force_row_wise= TRUE, # para reducir warnings
  verbosity= -100,

  seed= PARAM$semilla_primigenia,

  max_depth= -1L, # -1 significa no limitar,  por ahora lo dejo fijo    # Dejo que BO ajuste por num_leaves
  min_gain_to_split= 0, # min_gain_to_split >= 0
  min_sum_hessian_in_leaf= 0.001, #  min_sum_hessian_in_leaf >= 0.0
  lambda_l1= 0.0, # lambda_l1 >= 0.0
  lambda_l2= 0.0, # lambda_l2 >= 0.0
  max_bin= 31L, # lo debo dejar fijo, no participa de la BO

  bagging_fraction= 1.0, # 0.0 < bagging_fraction <= 1.0                Lu. A optimizar
  bagging_freq=0,                                                       # Hiperparámetro agregado. A optimizar.
  pos_bagging_fraction= 1.0, # 0.0 < pos_bagging_fraction <= 1.0
  neg_bagging_fraction= 1.0, # 0.0 < neg_bagging_fraction <= 1.0
  is_unbalance= FALSE, #
  scale_pos_weight= 10, # scale_pos_weight > 0.0                       Lu. A optimizar. Primer valor tomo 10

  drop_rate= 0.1, # 0.0 < neg_bagging_fraction <= 1.0
  max_drop= 50, # <=0 means no limit
  skip_drop= 0.5, # 0.0 <= skip_drop <= 1.0

  extra_trees= FALSE,

  num_iterations= 1200,                                                #Lu. A optimizar
  learning_rate= 0.1,                                                  #Lu. A optimizar. Cambie valor original 0.02
  feature_fraction= 0.5,                                               #Lu. A optimizar
  num_leaves= 512,                                                     #Lu. A optimizar. Cambie valor original 750
  min_data_in_leaf= 300                                               #Lu. A optimizar. Cambie valor original 300
)

In [ ]:
print(PARAM)      #Lu

$experimento
[1] 5940

$semilla_primigenia
[1] 120539

$kaggle
$kaggle$competencia
[1] "labo-i-2025-virtual-analista-sr"

$kaggle$cortes
[1] 10000 10500 11000 11500 12000


$trainingstrategy
$trainingstrategy$undersampling
[1] 0.5


$hyperparametertuning
$hyperparametertuning$xval_folds
[1] 5


$lgbm
$lgbm$param_fijos
$lgbm$param_fijos$boosting
[1] "gbdt"

$lgbm$param_fijos$objective
[1] "binary"

$lgbm$param_fijos$metric
[1] "auc"

$lgbm$param_fijos$first_metric_only
[1] FALSE

$lgbm$param_fijos$boost_from_average
[1] TRUE

$lgbm$param_fijos$feature_pre_filter
[1] FALSE

$lgbm$param_fijos$force_row_wise
[1] TRUE

$lgbm$param_fijos$verbosity
[1] -100

$lgbm$param_fijos$seed
[1] 120539

$lgbm$param_fijos$max_depth
[1] -1

$lgbm$param_fijos$min_gain_to_split
[1] 0

$lgbm$param_fijos$min_sum_hessian_in_leaf
[1] 0.001

$lgbm$param_fijos$lambda_l1
[1] 0

$lgbm$param_fijos$lambda_l2
[1] 0

$lgbm$param_fijos$max_bin
[1] 31

$lgbm$param_fijos$bagging_fraction
[1] 1

$lgbm$param_fijos$pos_bagging_fraction
[1] 1

$lgbm$param_fijos$neg_bagging_fraction
[1] 1

$lgbm$param_fijos$is_unbalance
[1] FALSE

$lgbm$param_fijos$scale_pos_weight
[1] 1

$lgbm$param_fijos$drop_rate
[1] 0.1

$lgbm$param_fijos$max_drop
[1] 50

$lgbm$param_fijos$skip_drop
[1] 0.5

$lgbm$param_fijos$extra_trees
[1] FALSE

$lgbm$param_fijos$num_iterations
[1] 1200

$lgbm$param_fijos$learning_rate
[1] 0.02

$lgbm$param_fijos$feature_fraction
[1] 0.5

$lgbm$param_fijos$num_leaves
[1] 750

$lgbm$param_fijos$min_data_in_leaf
[1] 5000

Aqui se definen los hiperparámetros de LightGBM que participan de la Bayesian Optimization
<br> si es un numero entero debe ir  makeIntegerParam
<br> si es un numero real (con decimales) debe ir  makeNumericParam
<br> es muy importante leer cuales son un lower y upper  permitidos y ademas razonables

In [7]:
# Aqui se cargan los bordes de los hiperparametros de la BO
PARAM$hypeparametertuning$hs <- makeParamSet(
  makeIntegerParam("num_iterations", lower= 120L, upper= 3000L),       # Lu. Rangos anteriores 8 - 2048
  makeNumericParam("learning_rate", lower= 0.005, upper= 0.1),          # Lu. Rangos anteriores 0.01 - 0.3
  makeNumericParam("feature_fraction", lower= 0.5, upper= 0.9),        # Lu. Rangos anteriores 0.1 - 1
  makeIntegerParam("min_data_in_leaf", lower= 150L, upper= 500L),       # Lu. Rangos anteriores 1 - 8000
  makeIntegerParam("num_leaves", lower= 8L, upper= 1024L),              # Lu. Rangos anteriores 8 - 2048
  makeNumericParam("bagging_fraction", lower= 0.6, upper= 1.0),        # Lu. Rangos anteriores 0.1 - 1
  makeIntegerParam("bagging_freq", lower= 0L, upper= 7L),             # Lu. Antes no estaba este parámetro
  makeIntegerParam("scale_pos_weight", lower= 1L, upper= 30L)         # Lu. Agregué para optimizar este hiperparámetro por clases altamente desbalanceadas.
)

A mayor cantidad de hiperparámetros, se debe aumentar las iteraciones de la Bayesian Optimization
<br> 30 es un valor muy tacaño, pero corre rápido
<br> deberia partir de 50, alcanzando los 100 si se dispone de tiempo

In [8]:
PARAM$hyperparametertuning$iteraciones <- 80    # iteraciones bayesianas. Es la cantidad de veces que prueba hiperparámetros (va iterando de forma inteligente, no prueba todas las combinaciones)

### 2.2.4  Preprocesamiento

In [9]:
# carpeta de trabajo

setwd("/content/buckets/b1/exp")
experimento_folder <- paste0("HT", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

In [10]:
# lectura del dataset

dataset <- fread("/content/datasets/dataset_pequeno.csv")

In [ ]:
dataset

       numero_de_cliente foto_mes active_quarter cliente_vip internet
1      29183733          202107   1              0           0
2      29184468          202107   1              0           0
3      29185245          202107   1              0           0
4      29186441          202107   1              0           0
5      29186475          202107   1              0           0
6      29187730          202107   1              0           0
7      29187764          202107   1              0           0
8      29187961          202107   1              0           0
9      29189899          202107   1              0           0
10     29189993          202107   1              0           0
11     29190113          202107   1              0           0
12     29192179          202107   1              0           0
13     29193101          202107   1              0           0
14     29193281          202107   1              0           0
15     29193324          202107   1              0           0
16     29195356          202107   1              0           0
17     29195433          202107   1              0           0
18     29196099          202107   1              0           0
19     29196902          202107   1              0           0
20     29198055          202107   1              0           0
21     29198891          202107   1              0           0
22     29199242          202107   1              0           0
23     29200335          202107   1              0           0
24     29200343          202107   1              0           0
25     29200514          202107   1              0           0
26     29200651          202107   1              0           0
27     29200727          202107   1              0           0
28     29200770          202107   1              0           0
29     29200984          202107   1              0           0
30     29201086          202107   1              0           0
⋮      ⋮                 ⋮        ⋮              ⋮           ⋮
329660 187967614         202109   1              0           0
329661 187969270         202109   0              0           0
329662 187989740         202109   0              0           0
329663 187999433         202109   1              0           0
329664 188009390         202109   0              0           0
329665 188009578         202109   0              0           0
329666 188015094         202109   1              0           0
329667 188017716         202109   1              0           0
329668 188019279         202109   0              0           0
329669 188031482         202109   1              0           0
329670 188042080         202109   0              0           0
329671 188054394         202109   1              0           0
329672 188055368         202109   0              0           0
329673 188057878         202109   1              0           0
329674 188061679         202109   0              0           0
329675 188062558         202109   0              0           0
329676 188064497         202109   1              0           0
329677 188071815         202109   1              0           0
329678 188073113         202109   1              0           0
329679 188074787         202109   0              0           0
329680 188084847         202109   1              0           0
329681 188096188         202109   1              0           0
329682 188097537         202109   0              0           0
329683 188100654         202109   0              0           0
329684 188101739         202109   0              0           0
329685 188115120         202109   1              0           0
329686 188116871         202109   1              0           0
329687 188122277         202109   1              0           0
329688 188128903         202109   0              0           0
329689 188136205         202109   0              0           0
       cliente_edad cliente_antiguedad mrentabilidad mrentabilidad_annual
1      46            99                 2016.19       32146.69
2      42           284                 1633.70       13781.99
3      55            23                 3759.73       24296.95
4      62           296                 2693.26       75390.56
5      66           326                 4567.63       56305.98
6      65           326                 7943.33      131725.70
7      56            91                 4861.51       46598.35
8      62           326                 6230.61       65485.56
9      60           379                 3497.72       70109.88
10     59            74                 4577.21        1736.68
11     43           183                 5680.01       -5983.54
12     55           315                 2559.97       18149.25
13     69           379                  890.03      138932.99
14     55           172                16834.93       58342.21
15     69           285                18151.35      126919.72
16     64           285                 3056.18       25824.79
17     45           200                -3874.33      -20402.71
18     59           326                 3074.80       21448.96
19     59           275                 8007.20       60279.40
20     53           283                -5141.43      -46180.97
21     55           326                 5720.68       37920.91
22     49           283                 1066.24        7607.69
23     46           262                 3526.73       36390.28
24     55           326                 1258.33      -29771.10
25     62           304                -6618.20      -24678.03
26     66             9                 1570.86       13395.31
27     74           261                21890.22      206711.08
28     59           276                 4747.88       88904.90
29     52           262                  373.76       -9880.90
30     44           285                -1673.83       -3786.63
⋮      ⋮            ⋮                  ⋮             ⋮
329660 22           1                     0.43          0.43
329661 35           1                     0.00          0.00
329662 51           1                     0.00          0.00
329663 27           1                   143.23        143.23
329664 24           1                     0.00          0.00
329665 24           1                     0.00          0.00
329666 49           1                     0.00          0.00
329667 24           1                    45.24         45.24
329668 39           1                     0.00          0.00
329669 35           1                   186.11        186.11
329670 74           1                     0.00          0.00
329671 40           1                     0.86          0.86
329672 41           1                  1915.23       1915.23
329673 26           1                    23.29         23.29
329674 22           1                    27.70         27.70
329675 29           1                     0.00          0.00
329676 20           1                     0.29          0.29
329677 36           1                   778.84        778.84
329678 30           1                     0.16          0.16
329679 64           1                     0.00          0.00
329680 37           1                  2479.05       2479.05
329681 41           1                     3.27          3.27
329682 38           1                     0.00          0.00
329683 37           1                     0.00          0.00
329684 36           1                     0.00          0.00
329685 48           1                   106.48        106.48
329686 30           1                   383.31        383.31
329687 23           1                   122.91        122.91
329688 31           1                     0.00          0.00
329689 54           1                     0.00          0.00
       mcomisiones ⋯ Visa_fultimo_cierre Visa_mpagado Visa_mpagospesos
1       1099.10    ⋯  3                       0.00     -27151.97
2        602.61    ⋯ 10                       0.00     -19268.21
3       2829.38    ⋯  3                       0.00      -8211.00
4       2493.68    ⋯ 24                   41585.05     -42723.62
5       3690.64    ⋯  3                       0.00     -51675.11
6       1166.58    ⋯ 24                   93724.31     -75205.28
7       1302.87    ⋯  3                       0.00    -207964.55
8       4971.69    ⋯  3                       0.00    -222510.54
9       2347.48    ⋯ 10                  149469.00    -219762.79
10      4063.79    ⋯  3                       0.00     -37494.64
11      2879.67    ⋯  3                       0.00    -331436.76
12      5036.66    ⋯ 10                       0.00     -28065.53
13      2649.61    ⋯ 10                   40521.29     -71529.52
14     17735.83    ⋯  3                       0.00     -35325.23
15       128.07    ⋯  3                       0.00      -7870.52
16      1185.53    ⋯  3                       0.00            NA
17       299.67    ⋯ 10                       0.00     -18019.43
18      3846.44    ⋯  3                       0.00     -49769.51
19      2714.41    ⋯ 10                       0.00     -49289.46
20       322.36    ⋯  3                       0.00     -34663.63
21       538.31    ⋯  3                       0.00     -29781.02
22       491.15    ⋯ NA                         NA            NA
23      1285.40    ⋯  3                       0.00     -24083.50
24      3347.30    ⋯  3                       0.00     -48122.77
25      1489.97    ⋯ 24                  153570.98    -144258.23
26       695.61    ⋯  3                       0.00     -52027.96
27      1203.60    ⋯ 10                       0.00     -73610.61
28       586.44    ⋯ 10                       0.00     -24310.96
29      3753.21    ⋯  3                       0.00     -33459.37
30       692.51    ⋯ 24                   35997.52     -40501.05
⋮      ⋮           ⋱ ⋮                   ⋮            ⋮
329660    0.00     ⋯  1                  0            NA
329661    0.00     ⋯  1                  0            NA
329662    0.00     ⋯  1                  0            NA
329663  103.04     ⋯  8                  0            NA
329664    0.00     ⋯  1                  0            NA
329665    0.00     ⋯ NA                  0            NA
329666    0.00     ⋯  1                  0            NA
329667    6.77     ⋯  1                  0            NA
329668    0.00     ⋯  1                  0            NA
329669    0.00     ⋯  8                  0            NA
329670    0.00     ⋯  1                  0            NA
329671    0.00     ⋯  1                  0            NA
329672 1910.64     ⋯  1                  0            NA
329673   16.28     ⋯  8                  0            NA
329674    0.00     ⋯  1                  0            NA
329675    0.00     ⋯ NA                  0            NA
329676    0.00     ⋯  1                  0            NA
329677    0.00     ⋯  1                  0            NA
329678    0.00     ⋯  1                  0            NA
329679    0.00     ⋯  1                  0            NA
329680  108.84     ⋯  1                  0            NA
329681    0.00     ⋯  8                  0            NA
329682    0.00     ⋯  1                  0            NA
329683    0.00     ⋯  8                  0            NA
329684    0.00     ⋯  1                  0            NA
329685   45.03     ⋯  8                  0             0
329686    0.00     ⋯  1                  0             0
329687    0.00     ⋯  8                  0            NA
329688    0.00     ⋯  1                  0            NA
329689    0.00     ⋯  1                  0            NA
       Visa_mpagosdolares Visa_fechaalta Visa_mconsumototal Visa_cconsumos
1        0.00             2995            10011.78           6
2        0.00             5722            15138.18           9
3        0.00              758            58080.27          10
4        0.00             8097            26541.92           8
5        0.00             2139            50304.17          16
6        1.00             6516            81931.93          16
7        0.00             1719            22464.65          14
8      620.51             8516            98717.05          27
9        0.00             9339           102991.71          43
10       0.00             2250            13246.57          15
11      11.24             2627            29682.24          13
12       0.00             4646            25251.35          13
13       0.00             2452            26315.26           5
14       0.00             3776            43132.42           6
15       0.00             6155             1595.28           2
16         NA             5869                  NA          NA
17      23.72             5791             1582.48           6
18       0.00             8280            24333.46           8
19       0.00             5119            29274.97          26
20       0.00             8042             9256.88           7
21       0.00             7668           104796.40          12
22         NA               NA                  NA          NA
23       0.00             2253            10032.38           3
24       3.53             8543            14093.25          11
25       0.00             9245            74579.17          11
26       0.00              261            60428.46           4
27       0.00             7958            27302.06           7
28       1.16             5386            10938.23           4
29       0.00             7954             1997.57           6
30       0.00             5196             2275.63           2
⋮      ⋮                  ⋮              ⋮                  ⋮
329660 NA                 11                 NA             NA
329661 NA                  7                 NA             NA
329662 NA                 18                 NA             NA
329663 NA                 11                 NA             NA
329664 NA                  2                 NA             NA
329665 NA                  2                 NA             NA
329666 NA                  1                 NA             NA
329667 NA                 17                 NA             NA
329668 NA                 11                 NA             NA
329669 NA                 11                 NA             NA
329670 NA                  1                 NA             NA
329671 NA                 22                 NA             NA
329672 NA                 21                 NA             NA
329673 NA                 17                 NA             NA
329674 NA                  2                 NA             NA
329675 NA                 15                 NA             NA
329676 NA                 11                 NA             NA
329677 NA                  4                 NA             NA
329678 NA                  1                 NA             NA
329679 NA                  2                 NA             NA
329680 NA                 24                 NA             NA
329681 NA                 10                 NA             NA
329682 NA                 10                 NA             NA
329683 NA                  9                 NA             NA
329684 NA                  7                 NA             NA
329685  0                 25             567.73              1
329686  0                 15               0.00              0
329687 NA                 16                 NA             NA
329688 NA                 11                 NA             NA
329689 NA                  1                 NA             NA
       Visa_cadelantosefectivo Visa_mpagominimo clase_ternaria
1       0                       2498.49         CONTINUA
2       0                       3178.83         CONTINUA
3       0                      26240.01         CONTINUA
4       0                       1782.96         CONTINUA
5       0                       3577.65         CONTINUA
6       0                       8480.79         CONTINUA
7       0                       2486.76         CONTINUA
8       0                       7706.61         CONTINUA
9       0                       8328.30         CONTINUA
10      0                      15729.93         CONTINUA
11      0                      23718.06         CONTINUA
12      0                       3612.84         CONTINUA
13      0                      17712.30         CONTINUA
14      0                       2275.62         CONTINUA
15      0                       1431.06         CONTINUA
16     NA                          0.00         CONTINUA
17      0                       3260.94         CONTINUA
18      0                       4715.46         CONTINUA
19      0                      74016.30         CONTINUA
20      0                       7084.92         CONTINUA
21      0                       6697.83         CONTINUA
22     NA                            NA         CONTINUA
23      0                       1642.20         CONTINUA
24      0                      18521.67         CONTINUA
25      0                      16386.81         CONTINUA
26      0                       3108.45         CONTINUA
27      0                       3214.02         CONTINUA
28      0                       2369.46         CONTINUA
29      0                      18533.40         CONTINUA
30      0                       7507.20         CONTINUA
⋮      ⋮                       ⋮                ⋮
329660 NA                       0.00
329661 NA                       0.00
329662 NA                       0.00
329663 NA                       0.00
329664 NA                       0.00
329665 NA                       0.00
329666 NA                       0.00
329667 NA                       0.00
329668 NA                       0.00
329669 NA                       0.00
329670 NA                       0.00
329671 NA                       0.00
329672 NA                       0.00
329673 NA                       0.00
329674 NA                       0.00
329675 NA                       0.00
329676 NA                       0.00
329677 NA                       0.00
329678 NA                       0.00
329679 NA                       0.00
329680 NA                       0.00
329681 NA                       0.00
329682 NA                       0.00
329683 NA                       0.00
329684 NA                       0.00
329685  0                      23.46
329686  0                       0.00
329687 NA                       0.00
329688 NA                       0.00
329689 NA                       0.00

In [11]:
dataset_train <- dataset[foto_mes %in% c(202107)]

In [ ]:
dataset_train
str(dataset_train)

       numero_de_cliente foto_mes active_quarter cliente_vip internet
1      29183733          202107   1              0           0
2      29184468          202107   1              0           0
3      29185245          202107   1              0           0
4      29186441          202107   1              0           0
5      29186475          202107   1              0           0
6      29187730          202107   1              0           0
7      29187764          202107   1              0           0
8      29187961          202107   1              0           0
9      29189899          202107   1              0           0
10     29189993          202107   1              0           0
11     29190113          202107   1              0           0
12     29192179          202107   1              0           0
13     29193101          202107   1              0           0
14     29193281          202107   1              0           0
15     29193324          202107   1              0           0
16     29195356          202107   1              0           0
17     29195433          202107   1              0           0
18     29196099          202107   1              0           0
19     29196902          202107   1              0           0
20     29198055          202107   1              0           0
21     29198891          202107   1              0           0
22     29199242          202107   1              0           0
23     29200335          202107   1              0           0
24     29200343          202107   1              0           0
25     29200514          202107   1              0           0
26     29200651          202107   1              0           0
27     29200727          202107   1              0           0
28     29200770          202107   1              0           0
29     29200984          202107   1              0           0
30     29201086          202107   1              0           0
⋮      ⋮                 ⋮        ⋮              ⋮           ⋮
164567 187313205         202107   1              0           0
164568 187314281         202107   0              0           0
164569 187325152         202107   0              0           0
164570 187327577         202107   0              0           0
164571 187340182         202107   1              0           0
164572 187343957         202107   1              0           0
164573 187346211         202107   1              0           0
164574 187348457         202107   1              0           0
164575 187349712         202107   1              0           0
164576 187355383         202107   0              0           0
164577 187366971         202107   0              0           0
164578 187369456         202107   1              0           0
164579 187372334         202107   0              0           0
164580 187377535         202107   0              0           0
164581 187378286         202107   0              0           0
164582 187380934         202107   0              0           0
164583 187386126         202107   0              0           0
164584 187388619         202107   1              0           0
164585 187398713         202107   1              0           0
164586 187402240         202107   0              0           0
164587 187405938         202107   0              0           0
164588 187409029         202107   0              0           0
164589 187429081         202107   1              0           0
164590 187429602         202107   0              0           0
164591 187432283         202107   0              0           0
164592 187434871         202107   1              0           0
164593 187444350         202107   1              0           0
164594 187445272         202107   1              0           0
164595 187460507         202107   1              0           0
164596 187466604         202107   0              0           0
       cliente_edad cliente_antiguedad mrentabilidad mrentabilidad_annual
1      46            99                 2016.19       32146.69
2      42           284                 1633.70       13781.99
3      55            23                 3759.73       24296.95
4      62           296                 2693.26       75390.56
5      66           326                 4567.63       56305.98
6      65           326                 7943.33      131725.70
7      56            91                 4861.51       46598.35
8      62           326                 6230.61       65485.56
9      60           379                 3497.72       70109.88
10     59            74                 4577.21        1736.68
11     43           183                 5680.01       -5983.54
12     55           315                 2559.97       18149.25
13     69           379                  890.03      138932.99
14     55           172                16834.93       58342.21
15     69           285                18151.35      126919.72
16     64           285                 3056.18       25824.79
17     45           200                -3874.33      -20402.71
18     59           326                 3074.80       21448.96
19     59           275                 8007.20       60279.40
20     53           283                -5141.43      -46180.97
21     55           326                 5720.68       37920.91
22     49           283                 1066.24        7607.69
23     46           262                 3526.73       36390.28
24     55           326                 1258.33      -29771.10
25     62           304                -6618.20      -24678.03
26     66             9                 1570.86       13395.31
27     74           261                21890.22      206711.08
28     59           276                 4747.88       88904.90
29     52           262                  373.76       -9880.90
30     44           285                -1673.83       -3786.63
⋮      ⋮            ⋮                  ⋮             ⋮
164567 29           1                   908.23        908.23
164568 27           1                    66.02         66.02
164569 65           1                     1.65          1.65
164570 46           1                     0.00          0.00
164571 57           1                  4854.19       4854.19
164572 44           1                  1746.51       1746.51
164573 37           1                     1.67          1.67
164574 31           1                   532.49        532.49
164575 20           1                     0.48          0.48
164576 35           1                     0.00          0.00
164577 38           1                     0.00          0.00
164578 35           1                    20.92         20.92
164579 35           1                     0.31          0.31
164580 22           1                     0.00          0.00
164581 22           1                     0.11          0.11
164582 39           1                     0.00          0.00
164583 38           1                     0.00          0.00
164584 28           1                    63.94         63.94
164585 21           1                   140.39        140.39
164586 62           1                     0.00          0.00
164587 27           1                     0.00          0.00
164588 28           1                     0.00          0.00
164589 35           1                    39.37         39.37
164590 29           1                     0.00          0.00
164591 54           1                     0.00          0.00
164592 69           1                  2392.75       2392.75
164593 35           1                   107.64        107.64
164594 34           1                   238.28        238.28
164595 41           1                  1187.43       1187.43
164596 43           1                     0.00          0.00
       mcomisiones ⋯ Visa_fultimo_cierre Visa_mpagado Visa_mpagospesos
1       1099.10    ⋯  3                       0.00     -27151.97
2        602.61    ⋯ 10                       0.00     -19268.21
3       2829.38    ⋯  3                       0.00      -8211.00
4       2493.68    ⋯ 24                   41585.05     -42723.62
5       3690.64    ⋯  3                       0.00     -51675.11
6       1166.58    ⋯ 24                   93724.31     -75205.28
7       1302.87    ⋯  3                       0.00    -207964.55
8       4971.69    ⋯  3                       0.00    -222510.54
9       2347.48    ⋯ 10                  149469.00    -219762.79
10      4063.79    ⋯  3                       0.00     -37494.64
11      2879.67    ⋯  3                       0.00    -331436.76
12      5036.66    ⋯ 10                       0.00     -28065.53
13      2649.61    ⋯ 10                   40521.29     -71529.52
14     17735.83    ⋯  3                       0.00     -35325.23
15       128.07    ⋯  3                       0.00      -7870.52
16      1185.53    ⋯  3                       0.00            NA
17       299.67    ⋯ 10                       0.00     -18019.43
18      3846.44    ⋯  3                       0.00     -49769.51
19      2714.41    ⋯ 10                       0.00     -49289.46
20       322.36    ⋯  3                       0.00     -34663.63
21       538.31    ⋯  3                       0.00     -29781.02
22       491.15    ⋯ NA                         NA            NA
23      1285.40    ⋯  3                       0.00     -24083.50
24      3347.30    ⋯  3                       0.00     -48122.77
25      1489.97    ⋯ 24                  153570.98    -144258.23
26       695.61    ⋯  3                       0.00     -52027.96
27      1203.60    ⋯ 10                       0.00     -73610.61
28       586.44    ⋯ 10                       0.00     -24310.96
29      3753.21    ⋯  3                       0.00     -33459.37
30       692.51    ⋯ 24                   35997.52     -40501.05
⋮      ⋮           ⋱ ⋮                   ⋮            ⋮
164567 978.09      ⋯  3                    0.00        0
164568   0.00      ⋯  3                    0.00       NA
164569   0.00      ⋯ NA                    0.00       NA
164570   0.00      ⋯ NA                      NA       NA
164571 527.76      ⋯  3                    0.00        0
164572   0.00      ⋯  3                    0.00       NA
164573   0.00      ⋯ 10                    0.00       NA
164574   0.00      ⋯  3                    0.00       NA
164575   0.00      ⋯  3                    0.00       NA
164576   0.00      ⋯  3                    0.00       NA
164577   0.00      ⋯  3                    0.00       NA
164578   0.00      ⋯  3                    0.00        0
164579   0.00      ⋯  3                    0.00       NA
164580   0.00      ⋯  3                    0.00       NA
164581   0.00      ⋯  3                    0.00       NA
164582   0.00      ⋯ NA                    0.00       NA
164583   0.00      ⋯ NA                      NA       NA
164584   0.00      ⋯ NA                    0.00       NA
164585   0.00      ⋯ NA                      NA       NA
164586   0.00      ⋯ 10                    0.00       NA
164587   0.00      ⋯  3                    0.00       NA
164588   0.00      ⋯ NA                    0.00       NA
164589   0.00      ⋯  3                    0.00       NA
164590   0.00      ⋯ 10                    0.00       NA
164591   0.00      ⋯  3                    0.00       NA
164592   0.00      ⋯  3                    0.00       NA
164593  74.55      ⋯ 10                  650.59        0
164594  70.84      ⋯  3                    0.00       NA
164595   0.00      ⋯  3                    0.00       NA
164596   0.00      ⋯ NA                      NA       NA
       Visa_mpagosdolares Visa_fechaalta Visa_mconsumototal Visa_cconsumos
1        0.00             2995            10011.78           6
2        0.00             5722            15138.18           9
3        0.00              758            58080.27          10
4        0.00             8097            26541.92           8
5        0.00             2139            50304.17          16
6        1.00             6516            81931.93          16
7        0.00             1719            22464.65          14
8      620.51             8516            98717.05          27
9        0.00             9339           102991.71          43
10       0.00             2250            13246.57          15
11      11.24             2627            29682.24          13
12       0.00             4646            25251.35          13
13       0.00             2452            26315.26           5
14       0.00             3776            43132.42           6
15       0.00             6155             1595.28           2
16         NA             5869                  NA          NA
17      23.72             5791             1582.48           6
18       0.00             8280            24333.46           8
19       0.00             5119            29274.97          26
20       0.00             8042             9256.88           7
21       0.00             7668           104796.40          12
22         NA               NA                  NA          NA
23       0.00             2253            10032.38           3
24       3.53             8543            14093.25          11
25       0.00             9245            74579.17          11
26       0.00              261            60428.46           4
27       0.00             7958            27302.06           7
28       1.16             5386            10938.23           4
29       0.00             7954             1997.57           6
30       0.00             5196             2275.63           2
⋮      ⋮                  ⋮              ⋮                  ⋮
164567  0                 16              382.82             1
164568 NA                 11                  NA            NA
164569 NA                  9                  NA            NA
164570 NA                 NA                  NA            NA
164571  0                 25                0.00             0
164572 NA                 17                  NA            NA
164573 NA                 17                  NA            NA
164574 NA                 12                  NA            NA
164575 NA                 12                  NA            NA
164576 NA                  4                  NA            NA
164577 NA                 24                  NA            NA
164578  0                 11             8797.50             1
164579 NA                  4                  NA            NA
164580 NA                 11                  NA            NA
164581 NA                  3                  NA            NA
164582 NA                  6                  NA            NA
164583 NA                 NA                  NA            NA
164584 NA                  6                  NA            NA
164585 NA                 NA                  NA            NA
164586 NA                 17                  NA            NA
164587 NA                 11                  NA            NA
164588 NA                  6                  NA            NA
164589 NA                 18                  NA            NA
164590 NA                 11                  NA            NA
164591 NA                  5                  NA            NA
164592 NA                 10                  NA            NA
164593  0                 30              108.19             3
164594 NA                  6                  NA            NA
164595 NA                 11                  NA            NA
164596 NA                 NA                  NA            NA
       Visa_cadelantosefectivo Visa_mpagominimo clase_ternaria
1       0                       2498.49         CONTINUA
2       0                       3178.83         CONTINUA
3       0                      26240.01         CONTINUA
4       0                       1782.96         CONTINUA
5       0                       3577.65         CONTINUA
6       0                       8480.79         CONTINUA
7       0                       2486.76         CONTINUA
8       0                       7706.61         CONTINUA
9       0                       8328.30         CONTINUA
10      0                      15729.93         CONTINUA
11      0                      23718.06         CONTINUA
12      0                       3612.84         CONTINUA
13      0                      17712.30         CONTINUA
14      0                       2275.62         CONTINUA
15      0                       1431.06         CONTINUA
16     NA                          0.00         CONTINUA
17      0                       3260.94         CONTINUA
18      0                       4715.46         CONTINUA
19      0                      74016.30         CONTINUA
20      0                       7084.92         CONTINUA
21      0                       6697.83         CONTINUA
22     NA                            NA         CONTINUA
23      0                       1642.20         CONTINUA
24      0                      18521.67         CONTINUA
25      0                      16386.81         CONTINUA
26      0                       3108.45         CONTINUA
27      0                       3214.02         CONTINUA
28      0                       2369.46         CONTINUA
29      0                      18533.40         CONTINUA
30      0                       7507.20         CONTINUA
⋮      ⋮                       ⋮                ⋮
164567  0                      3038.07          CONTINUA
164568 NA                         0.00          CONTINUA
164569 NA                         0.00          CONTINUA
164570 NA                           NA          CONTINUA
164571  0                      1313.76          CONTINUA
164572 NA                         0.00          CONTINUA
164573 NA                         0.00          CONTINUA
164574 NA                         0.00          CONTINUA
164575 NA                         0.00          CONTINUA
164576 NA                         0.00          CONTINUA
164577 NA                         0.00          BAJA+1
164578  0                       457.47          CONTINUA
164579 NA                         0.00          CONTINUA
164580 NA                         0.00          CONTINUA
164581 NA                         0.00          CONTINUA
164582 NA                         0.00          CONTINUA
164583 NA                           NA          CONTINUA
164584 NA                         0.00          CONTINUA
164585 NA                           NA          CONTINUA
164586 NA                         0.00          CONTINUA
164587 NA                         0.00          CONTINUA
164588 NA                         0.00          CONTINUA
164589 NA                         0.00          CONTINUA
164590 NA                         0.00          CONTINUA
164591 NA                         0.00          CONTINUA
164592 NA                         0.00          CONTINUA
164593  0                       222.87          CONTINUA
164594 NA                         0.00          CONTINUA
164595 NA                         0.00          CONTINUA
164596 NA                           NA          CONTINUA

Classes ‘data.table’ and 'data.frame':	164596 obs. of  155 variables:
 $ numero_de_cliente                   : int  29183733 29184468 29185245 29186441 29186475 29187730 29187764 29187961 29189899 29189993 ...
 $ foto_mes                            : int  202107 202107 202107 202107 202107 202107 202107 202107 202107 202107 ...
 $ active_quarter                      : int  1 1 1 1 1 1 1 1 1 1 ...
 $ cliente_vip                         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ internet                            : int  0 0 0 0 0 0 0 0 0 0 ...
 $ cliente_edad                        : int  46 42 55 62 66 65 56 62 60 59 ...
 $ cliente_antiguedad                  : int  99 284 23 296 326 326 91 326 379 74 ...
 $ mrentabilidad                       : num  2016 1634 3760 2693 4568 ...
 $ mrentabilidad_annual                : num  32147 13782 24297 75391 56306 ...
 $ mcomisiones                         : num  1099 603 2829 2494 3691 ...
 $ mactivos_margen                     : num  -113 -241 746 -2909 -1521 ...
 $ mpasivos_margen                     : num  894.6 1120 47.6 3079.4 2268.7 ...
 $ cproductos                          : int  8 9 7 7 8 8 10 7 12 9 ...
 $ tcuentas                            : int  1 1 1 1 1 1 1 1 1 1 ...
 $ ccuenta_corriente                   : int  1 1 1 1 1 1 1 1 2 1 ...
 $ mcuenta_corriente_adicional         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ mcuenta_corriente                   : num  -542 0 -9579 0 0 ...
 $ ccaja_ahorro                        : int  2 2 2 2 3 2 2 2 4 2 ...
 $ mcaja_ahorro                        : num  4.02e+04 6.47e+04 4.90e-01 1.90e+05 9.94e+04 ...
 $ mcaja_ahorro_adicional              : num  0 0 0 0 21678 ...
 $ mcaja_ahorro_dolares                : num  11341 35486 0 33447 34196 ...
 $ cdescubierto_preacordado            : int  1 1 1 1 1 1 1 1 1 1 ...
 $ mcuentas_saldo                      : num  20380 133752 -3659 222688 91157 ...
 $ ctarjeta_debito                     : int  1 1 1 7 2 2 1 1 2 1 ...
 $ ctarjeta_debito_transacciones       : int  4 16 0 0 14 1 37 0 16 29 ...
 $ mautoservicio                       : num  58903 26462 0 0 15621 ...
 $ ctarjeta_visa                       : int  1 1 1 1 1 1 1 1 1 1 ...
 $ ctarjeta_visa_transacciones         : int  10 13 11 10 20 21 20 42 65 16 ...
 $ mtarjeta_visa_consumo               : num  23289 26237 58644 42453 60819 ...
 $ ctarjeta_master                     : int  1 1 1 1 1 1 1 1 1 0 ...
 $ ctarjeta_master_transacciones       : int  19 0 0 0 0 0 1 2 0 0 ...
 $ mtarjeta_master_consumo             : num  33110 0 0 0 0 ...
 $ cprestamos_personales               : int  0 1 0 0 0 0 2 0 0 0 ...
 $ mprestamos_personales               : num  0 76650 0 0 0 ...
 $ cprestamos_prendarios               : int  0 0 0 0 0 0 0 0 0 1 ...
 $ mprestamos_prendarios               : num  0 0 0 0 0 ...
 $ cprestamos_hipotecarios             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ mprestamos_hipotecarios             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cplazo_fijo                         : int  0 0 0 0 0 0 0 0 3 0 ...
 $ mplazo_fijo_dolares                 : num  0 0 0 0 0 ...
 $ mplazo_fijo_pesos                   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cinversion1                         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ minversion1_pesos                   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ minversion1_dolares                 : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cinversion2                         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ minversion2                         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cseguro_vida                        : int  0 1 0 0 0 0 0 0 0 1 ...
 $ cseguro_auto                        : int  0 0 0 0 0 0 1 0 0 0 ...
 $ cseguro_vivienda                    : int  1 0 0 0 0 0 0 0 0 0 ...
 $ cseguro_accidentes_personales       : int  0 0 0 0 0 0 0 0 0 1 ...
 $ ccaja_seguridad                     : int  0 0 0 1 0 1 0 0 1 0 ...
 $ cpayroll_trx                        : int  1 1 0 0 0 2 1 0 0 0 ...
 $ mpayroll                            : num  113970 87918 0 0 0 ...
 $ mpayroll2                           : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cpayroll2_trx                       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ ccuenta_debitos_automaticos         : int  2 2 0 1 5 2 1 0 0 2 ...
 $ mcuenta_debitos_automaticos         : num  19296 4837 0 1373 5534 ...
 $ ctarjeta_visa_debitos_automaticos   : int  4 5 0 7 3 9 5 7 31 12 ...
 $ mttarjeta_visa_debitos_automaticos  : num  10014 6982 0 25255 6617 ...
 $ ctarjeta_master_debitos_automaticos : int  6 0 0 0 0 0 0 1 0 0 ...
 $ mttarjeta_master_debitos_automaticos: num  5116 0 0 0 0 ...
 $ cpagodeservicios                    : int  0 0 0 0 0 0 0 0 0 0 ...
 $ mpagodeservicios                    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cpagomiscuentas                     : int  0 0 0 6 10 5 4 14 3 1 ...
 $ mpagomiscuentas                     : num  0 0 0 28307 35971 ...
 $ ccajeros_propios_descuentos         : int  0 0 0 0 0 0 1 0 0 0 ...
 $ mcajeros_propios_descuentos         : num  0 0 0 0 0 ...
 $ ctarjeta_visa_descuentos            : int  1 0 0 0 0 1 0 0 0 0 ...
 $ mtarjeta_visa_descuentos            : num  NA 0 0 0 0 NA 0 0 0 0 ...
 $ ctarjeta_master_descuentos          : int  0 0 0 0 0 0 1 0 0 0 ...
 $ mtarjeta_master_descuentos          : num  0 0 0 0 0 0 0 0 0 0 ...
 $ ccomisiones_mantenimiento           : int  0 0 1 1 1 0 0 1 0 1 ...
 $ mcomisiones_mantenimiento           : num  0 0 3007 2129 2794 ...
 $ ccomisiones_otras                   : int  14 10 6 8 13 8 8 8 10 16 ...
 $ mcomisiones_otras                   : num  1099 603 2829 2494 3691 ...
 $ cforex                              : int  0 1 0 0 0 0 0 0 1 0 ...
 $ cforex_buy                          : int  0 0 0 0 0 0 0 0 0 0 ...
 $ mforex_buy                          : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cforex_sell                         : int  0 1 0 0 0 0 0 0 1 0 ...
 $ mforex_sell                         : num  0 235 0 0 0 ...
 $ ctransferencias_recibidas           : int  1 1 0 0 2 0 5 1 5 11 ...
 $ mtransferencias_recibidas           : num  3120 87918 0 0 54235 ...
 $ ctransferencias_emitidas            : int  3 4 0 0 5 2 14 1 3 2 ...
 $ mtransferencias_emitidas            : num  26979 10088 0 0 154660 ...
 $ cextraccion_autoservicio            : int  0 1 0 0 3 9 4 0 3 0 ...
 $ mextraccion_autoservicio            : num  0 5865 0 0 70380 ...
 $ ccheques_depositados                : int  0 0 0 2 0 0 0 0 0 1 ...
 $ mcheques_depositados                : num  0 0 0 105570 0 ...
 $ ccheques_emitidos                   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ mcheques_emitidos                   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ ccheques_depositados_rechazados     : int  0 0 0 0 0 0 0 0 0 0 ...
 $ mcheques_depositados_rechazados     : num  0 0 0 0 0 0 0 0 0 0 ...
 $ ccheques_emitidos_rechazados        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ mcheques_emitidos_rechazados        : num  0 0 0 0 0 0 0 0 0 0 ...
 $ tcallcenter                         : int  0 0 0 0 0 0 0 0 1 0 ...
 $ ccallcenter_transacciones           : int  0 0 0 0 0 0 0 0 3 0 ...
 $ thomebanking                        : int  1 0 1 1 1 1 1 1 1 1 ...
 $ chomebanking_transacciones          : int  4 4 6 21 96 69 52 150 126 34 ...
 $ ccajas_transacciones                : int  0 0 0 0 0 0 0 0 0 0 ...
  [list output truncated]
 - attr(*, ".internal.selfref")=<externalptr>

In [12]:
# paso la clase a binaria que tome valores {0,1}  enteros     Agrega una nueva columna "clase01"
#  BAJA+1 y BAJA+2  son  1,   CONTINUA es 0

dataset_train[,
  clase01 := ifelse(clase_ternaria %in% c("BAJA+2","BAJA+1"), 1L, 0L)
]

In [13]:
# Contar por valor de clase01
dataset_train[, .N, by = clase01]

  clase01 N
1 0       162211
2 1         2385

In [ ]:
dataset_train
str(dataset_train)

       numero_de_cliente foto_mes active_quarter cliente_vip internet
1      29183733          202107   1              0           0
2      29184468          202107   1              0           0
3      29185245          202107   1              0           0
4      29186441          202107   1              0           0
5      29186475          202107   1              0           0
6      29187730          202107   1              0           0
7      29187764          202107   1              0           0
8      29187961          202107   1              0           0
9      29189899          202107   1              0           0
10     29189993          202107   1              0           0
11     29190113          202107   1              0           0
12     29192179          202107   1              0           0
13     29193101          202107   1              0           0
14     29193281          202107   1              0           0
15     29193324          202107   1              0           0
16     29195356          202107   1              0           0
17     29195433          202107   1              0           0
18     29196099          202107   1              0           0
19     29196902          202107   1              0           0
20     29198055          202107   1              0           0
21     29198891          202107   1              0           0
22     29199242          202107   1              0           0
23     29200335          202107   1              0           0
24     29200343          202107   1              0           0
25     29200514          202107   1              0           0
26     29200651          202107   1              0           0
27     29200727          202107   1              0           0
28     29200770          202107   1              0           0
29     29200984          202107   1              0           0
30     29201086          202107   1              0           0
⋮      ⋮                 ⋮        ⋮              ⋮           ⋮
164567 187313205         202107   1              0           0
164568 187314281         202107   0              0           0
164569 187325152         202107   0              0           0
164570 187327577         202107   0              0           0
164571 187340182         202107   1              0           0
164572 187343957         202107   1              0           0
164573 187346211         202107   1              0           0
164574 187348457         202107   1              0           0
164575 187349712         202107   1              0           0
164576 187355383         202107   0              0           0
164577 187366971         202107   0              0           0
164578 187369456         202107   1              0           0
164579 187372334         202107   0              0           0
164580 187377535         202107   0              0           0
164581 187378286         202107   0              0           0
164582 187380934         202107   0              0           0
164583 187386126         202107   0              0           0
164584 187388619         202107   1              0           0
164585 187398713         202107   1              0           0
164586 187402240         202107   0              0           0
164587 187405938         202107   0              0           0
164588 187409029         202107   0              0           0
164589 187429081         202107   1              0           0
164590 187429602         202107   0              0           0
164591 187432283         202107   0              0           0
164592 187434871         202107   1              0           0
164593 187444350         202107   1              0           0
164594 187445272         202107   1              0           0
164595 187460507         202107   1              0           0
164596 187466604         202107   0              0           0
       cliente_edad cliente_antiguedad mrentabilidad mrentabilidad_annual
1      46            99                 2016.19       32146.69
2      42           284                 1633.70       13781.99
3      55            23                 3759.73       24296.95
4      62           296                 2693.26       75390.56
5      66           326                 4567.63       56305.98
6      65           326                 7943.33      131725.70
7      56            91                 4861.51       46598.35
8      62           326                 6230.61       65485.56
9      60           379                 3497.72       70109.88
10     59            74                 4577.21        1736.68
11     43           183                 5680.01       -5983.54
12     55           315                 2559.97       18149.25
13     69           379                  890.03      138932.99
14     55           172                16834.93       58342.21
15     69           285                18151.35      126919.72
16     64           285                 3056.18       25824.79
17     45           200                -3874.33      -20402.71
18     59           326                 3074.80       21448.96
19     59           275                 8007.20       60279.40
20     53           283                -5141.43      -46180.97
21     55           326                 5720.68       37920.91
22     49           283                 1066.24        7607.69
23     46           262                 3526.73       36390.28
24     55           326                 1258.33      -29771.10
25     62           304                -6618.20      -24678.03
26     66             9                 1570.86       13395.31
27     74           261                21890.22      206711.08
28     59           276                 4747.88       88904.90
29     52           262                  373.76       -9880.90
30     44           285                -1673.83       -3786.63
⋮      ⋮            ⋮                  ⋮             ⋮
164567 29           1                   908.23        908.23
164568 27           1                    66.02         66.02
164569 65           1                     1.65          1.65
164570 46           1                     0.00          0.00
164571 57           1                  4854.19       4854.19
164572 44           1                  1746.51       1746.51
164573 37           1                     1.67          1.67
164574 31           1                   532.49        532.49
164575 20           1                     0.48          0.48
164576 35           1                     0.00          0.00
164577 38           1                     0.00          0.00
164578 35           1                    20.92         20.92
164579 35           1                     0.31          0.31
164580 22           1                     0.00          0.00
164581 22           1                     0.11          0.11
164582 39           1                     0.00          0.00
164583 38           1                     0.00          0.00
164584 28           1                    63.94         63.94
164585 21           1                   140.39        140.39
164586 62           1                     0.00          0.00
164587 27           1                     0.00          0.00
164588 28           1                     0.00          0.00
164589 35           1                    39.37         39.37
164590 29           1                     0.00          0.00
164591 54           1                     0.00          0.00
164592 69           1                  2392.75       2392.75
164593 35           1                   107.64        107.64
164594 34           1                   238.28        238.28
164595 41           1                  1187.43       1187.43
164596 43           1                     0.00          0.00
       mcomisiones ⋯ Visa_mpagado Visa_mpagospesos Visa_mpagosdolares
1       1099.10    ⋯      0.00     -27151.97         0.00
2        602.61    ⋯      0.00     -19268.21         0.00
3       2829.38    ⋯      0.00      -8211.00         0.00
4       2493.68    ⋯  41585.05     -42723.62         0.00
5       3690.64    ⋯      0.00     -51675.11         0.00
6       1166.58    ⋯  93724.31     -75205.28         1.00
7       1302.87    ⋯      0.00    -207964.55         0.00
8       4971.69    ⋯      0.00    -222510.54       620.51
9       2347.48    ⋯ 149469.00    -219762.79         0.00
10      4063.79    ⋯      0.00     -37494.64         0.00
11      2879.67    ⋯      0.00    -331436.76        11.24
12      5036.66    ⋯      0.00     -28065.53         0.00
13      2649.61    ⋯  40521.29     -71529.52         0.00
14     17735.83    ⋯      0.00     -35325.23         0.00
15       128.07    ⋯      0.00      -7870.52         0.00
16      1185.53    ⋯      0.00            NA           NA
17       299.67    ⋯      0.00     -18019.43        23.72
18      3846.44    ⋯      0.00     -49769.51         0.00
19      2714.41    ⋯      0.00     -49289.46         0.00
20       322.36    ⋯      0.00     -34663.63         0.00
21       538.31    ⋯      0.00     -29781.02         0.00
22       491.15    ⋯        NA            NA           NA
23      1285.40    ⋯      0.00     -24083.50         0.00
24      3347.30    ⋯      0.00     -48122.77         3.53
25      1489.97    ⋯ 153570.98    -144258.23         0.00
26       695.61    ⋯      0.00     -52027.96         0.00
27      1203.60    ⋯      0.00     -73610.61         0.00
28       586.44    ⋯      0.00     -24310.96         1.16
29      3753.21    ⋯      0.00     -33459.37         0.00
30       692.51    ⋯  35997.52     -40501.05         0.00
⋮      ⋮           ⋱ ⋮            ⋮                ⋮
164567 978.09      ⋯   0.00        0                0
164568   0.00      ⋯   0.00       NA               NA
164569   0.00      ⋯   0.00       NA               NA
164570   0.00      ⋯     NA       NA               NA
164571 527.76      ⋯   0.00        0                0
164572   0.00      ⋯   0.00       NA               NA
164573   0.00      ⋯   0.00       NA               NA
164574   0.00      ⋯   0.00       NA               NA
164575   0.00      ⋯   0.00       NA               NA
164576   0.00      ⋯   0.00       NA               NA
164577   0.00      ⋯   0.00       NA               NA
164578   0.00      ⋯   0.00        0                0
164579   0.00      ⋯   0.00       NA               NA
164580   0.00      ⋯   0.00       NA               NA
164581   0.00      ⋯   0.00       NA               NA
164582   0.00      ⋯   0.00       NA               NA
164583   0.00      ⋯     NA       NA               NA
164584   0.00      ⋯   0.00       NA               NA
164585   0.00      ⋯     NA       NA               NA
164586   0.00      ⋯   0.00       NA               NA
164587   0.00      ⋯   0.00       NA               NA
164588   0.00      ⋯   0.00       NA               NA
164589   0.00      ⋯   0.00       NA               NA
164590   0.00      ⋯   0.00       NA               NA
164591   0.00      ⋯   0.00       NA               NA
164592   0.00      ⋯   0.00       NA               NA
164593  74.55      ⋯ 650.59        0                0
164594  70.84      ⋯   0.00       NA               NA
164595   0.00      ⋯   0.00       NA               NA
164596   0.00      ⋯     NA       NA               NA
       Visa_fechaalta Visa_mconsumototal Visa_cconsumos Visa_cadelantosefectivo
1      2995            10011.78           6              0
2      5722            15138.18           9              0
3       758            58080.27          10              0
4      8097            26541.92           8              0
5      2139            50304.17          16              0
6      6516            81931.93          16              0
7      1719            22464.65          14              0
8      8516            98717.05          27              0
9      9339           102991.71          43              0
10     2250            13246.57          15              0
11     2627            29682.24          13              0
12     4646            25251.35          13              0
13     2452            26315.26           5              0
14     3776            43132.42           6              0
15     6155             1595.28           2              0
16     5869                  NA          NA             NA
17     5791             1582.48           6              0
18     8280            24333.46           8              0
19     5119            29274.97          26              0
20     8042             9256.88           7              0
21     7668           104796.40          12              0
22       NA                  NA          NA             NA
23     2253            10032.38           3              0
24     8543            14093.25          11              0
25     9245            74579.17          11              0
26      261            60428.46           4              0
27     7958            27302.06           7              0
28     5386            10938.23           4              0
29     7954             1997.57           6              0
30     5196             2275.63           2              0
⋮      ⋮              ⋮                  ⋮              ⋮
164567 16              382.82             1              0
164568 11                  NA            NA             NA
164569  9                  NA            NA             NA
164570 NA                  NA            NA             NA
164571 25                0.00             0              0
164572 17                  NA            NA             NA
164573 17                  NA            NA             NA
164574 12                  NA            NA             NA
164575 12                  NA            NA             NA
164576  4                  NA            NA             NA
164577 24                  NA            NA             NA
164578 11             8797.50             1              0
164579  4                  NA            NA             NA
164580 11                  NA            NA             NA
164581  3                  NA            NA             NA
164582  6                  NA            NA             NA
164583 NA                  NA            NA             NA
164584  6                  NA            NA             NA
164585 NA                  NA            NA             NA
164586 17                  NA            NA             NA
164587 11                  NA            NA             NA
164588  6                  NA            NA             NA
164589 18                  NA            NA             NA
164590 11                  NA            NA             NA
164591  5                  NA            NA             NA
164592 10                  NA            NA             NA
164593 30              108.19             3              0
164594  6                  NA            NA             NA
164595 11                  NA            NA             NA
164596 NA                  NA            NA             NA
       Visa_mpagominimo clase_ternaria clase01
1       2498.49         CONTINUA       0
2       3178.83         CONTINUA       0
3      26240.01         CONTINUA       0
4       1782.96         CONTINUA       0
5       3577.65         CONTINUA       0
6       8480.79         CONTINUA       0
7       2486.76         CONTINUA       0
8       7706.61         CONTINUA       0
9       8328.30         CONTINUA       0
10     15729.93         CONTINUA       0
11     23718.06         CONTINUA       0
12      3612.84         CONTINUA       0
13     17712.30         CONTINUA       0
14      2275.62         CONTINUA       0
15      1431.06         CONTINUA       0
16         0.00         CONTINUA       0
17      3260.94         CONTINUA       0
18      4715.46         CONTINUA       0
19     74016.30         CONTINUA       0
20      7084.92         CONTINUA       0
21      6697.83         CONTINUA       0
22           NA         CONTINUA       0
23      1642.20         CONTINUA       0
24     18521.67         CONTINUA       0
25     16386.81         CONTINUA       0
26      3108.45         CONTINUA       0
27      3214.02         CONTINUA       0
28      2369.46         CONTINUA       0
29     18533.40         CONTINUA       0
30      7507.20         CONTINUA       0
⋮      ⋮                ⋮              ⋮
164567 3038.07          CONTINUA       0
164568    0.00          CONTINUA       0
164569    0.00          CONTINUA       0
164570      NA          CONTINUA       0
164571 1313.76          CONTINUA       0
164572    0.00          CONTINUA       0
164573    0.00          CONTINUA       0
164574    0.00          CONTINUA       0
164575    0.00          CONTINUA       0
164576    0.00          CONTINUA       0
164577    0.00          BAJA+1         1
164578  457.47          CONTINUA       0
164579    0.00          CONTINUA       0
164580    0.00          CONTINUA       0
164581    0.00          CONTINUA       0
164582    0.00          CONTINUA       0
164583      NA          CONTINUA       0
164584    0.00          CONTINUA       0
164585      NA          CONTINUA       0
164586    0.00          CONTINUA       0
164587    0.00          CONTINUA       0
164588    0.00          CONTINUA       0
164589    0.00          CONTINUA       0
164590    0.00          CONTINUA       0
164591    0.00          CONTINUA       0
164592    0.00          CONTINUA       0
164593  222.87          CONTINUA       0
164594    0.00          CONTINUA       0
164595    0.00          CONTINUA       0
164596      NA          CONTINUA       0

Classes ‘data.table’ and 'data.frame':	164596 obs. of  156 variables:
 $ numero_de_cliente                   : int  29183733 29184468 29185245 29186441 29186475 29187730 29187764 29187961 29189899 29189993 ...
 $ foto_mes                            : int  202107 202107 202107 202107 202107 202107 202107 202107 202107 202107 ...
 $ active_quarter                      : int  1 1 1 1 1 1 1 1 1 1 ...
 $ cliente_vip                         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ internet                            : int  0 0 0 0 0 0 0 0 0 0 ...
 $ cliente_edad                        : int  46 42 55 62 66 65 56 62 60 59 ...
 $ cliente_antiguedad                  : int  99 284 23 296 326 326 91 326 379 74 ...
 $ mrentabilidad                       : num  2016 1634 3760 2693 4568 ...
 $ mrentabilidad_annual                : num  32147 13782 24297 75391 56306 ...
 $ mcomisiones                         : num  1099 603 2829 2494 3691 ...
 $ mactivos_margen                     : num  -113 -241 746 -2909 -1521 ...
 $ mpasivos_margen                     : num  894.6 1120 47.6 3079.4 2268.7 ...
 $ cproductos                          : int  8 9 7 7 8 8 10 7 12 9 ...
 $ tcuentas                            : int  1 1 1 1 1 1 1 1 1 1 ...
 $ ccuenta_corriente                   : int  1 1 1 1 1 1 1 1 2 1 ...
 $ mcuenta_corriente_adicional         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ mcuenta_corriente                   : num  -542 0 -9579 0 0 ...
 $ ccaja_ahorro                        : int  2 2 2 2 3 2 2 2 4 2 ...
 $ mcaja_ahorro                        : num  4.02e+04 6.47e+04 4.90e-01 1.90e+05 9.94e+04 ...
 $ mcaja_ahorro_adicional              : num  0 0 0 0 21678 ...
 $ mcaja_ahorro_dolares                : num  11341 35486 0 33447 34196 ...
 $ cdescubierto_preacordado            : int  1 1 1 1 1 1 1 1 1 1 ...
 $ mcuentas_saldo                      : num  20380 133752 -3659 222688 91157 ...
 $ ctarjeta_debito                     : int  1 1 1 7 2 2 1 1 2 1 ...
 $ ctarjeta_debito_transacciones       : int  4 16 0 0 14 1 37 0 16 29 ...
 $ mautoservicio                       : num  58903 26462 0 0 15621 ...
 $ ctarjeta_visa                       : int  1 1 1 1 1 1 1 1 1 1 ...
 $ ctarjeta_visa_transacciones         : int  10 13 11 10 20 21 20 42 65 16 ...
 $ mtarjeta_visa_consumo               : num  23289 26237 58644 42453 60819 ...
 $ ctarjeta_master                     : int  1 1 1 1 1 1 1 1 1 0 ...
 $ ctarjeta_master_transacciones       : int  19 0 0 0 0 0 1 2 0 0 ...
 $ mtarjeta_master_consumo             : num  33110 0 0 0 0 ...
 $ cprestamos_personales               : int  0 1 0 0 0 0 2 0 0 0 ...
 $ mprestamos_personales               : num  0 76650 0 0 0 ...
 $ cprestamos_prendarios               : int  0 0 0 0 0 0 0 0 0 1 ...
 $ mprestamos_prendarios               : num  0 0 0 0 0 ...
 $ cprestamos_hipotecarios             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ mprestamos_hipotecarios             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cplazo_fijo                         : int  0 0 0 0 0 0 0 0 3 0 ...
 $ mplazo_fijo_dolares                 : num  0 0 0 0 0 ...
 $ mplazo_fijo_pesos                   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cinversion1                         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ minversion1_pesos                   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ minversion1_dolares                 : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cinversion2                         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ minversion2                         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cseguro_vida                        : int  0 1 0 0 0 0 0 0 0 1 ...
 $ cseguro_auto                        : int  0 0 0 0 0 0 1 0 0 0 ...
 $ cseguro_vivienda                    : int  1 0 0 0 0 0 0 0 0 0 ...
 $ cseguro_accidentes_personales       : int  0 0 0 0 0 0 0 0 0 1 ...
 $ ccaja_seguridad                     : int  0 0 0 1 0 1 0 0 1 0 ...
 $ cpayroll_trx                        : int  1 1 0 0 0 2 1 0 0 0 ...
 $ mpayroll                            : num  113970 87918 0 0 0 ...
 $ mpayroll2                           : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cpayroll2_trx                       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ ccuenta_debitos_automaticos         : int  2 2 0 1 5 2 1 0 0 2 ...
 $ mcuenta_debitos_automaticos         : num  19296 4837 0 1373 5534 ...
 $ ctarjeta_visa_debitos_automaticos   : int  4 5 0 7 3 9 5 7 31 12 ...
 $ mttarjeta_visa_debitos_automaticos  : num  10014 6982 0 25255 6617 ...
 $ ctarjeta_master_debitos_automaticos : int  6 0 0 0 0 0 0 1 0 0 ...
 $ mttarjeta_master_debitos_automaticos: num  5116 0 0 0 0 ...
 $ cpagodeservicios                    : int  0 0 0 0 0 0 0 0 0 0 ...
 $ mpagodeservicios                    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cpagomiscuentas                     : int  0 0 0 6 10 5 4 14 3 1 ...
 $ mpagomiscuentas                     : num  0 0 0 28307 35971 ...
 $ ccajeros_propios_descuentos         : int  0 0 0 0 0 0 1 0 0 0 ...
 $ mcajeros_propios_descuentos         : num  0 0 0 0 0 ...
 $ ctarjeta_visa_descuentos            : int  1 0 0 0 0 1 0 0 0 0 ...
 $ mtarjeta_visa_descuentos            : num  NA 0 0 0 0 NA 0 0 0 0 ...
 $ ctarjeta_master_descuentos          : int  0 0 0 0 0 0 1 0 0 0 ...
 $ mtarjeta_master_descuentos          : num  0 0 0 0 0 0 0 0 0 0 ...
 $ ccomisiones_mantenimiento           : int  0 0 1 1 1 0 0 1 0 1 ...
 $ mcomisiones_mantenimiento           : num  0 0 3007 2129 2794 ...
 $ ccomisiones_otras                   : int  14 10 6 8 13 8 8 8 10 16 ...
 $ mcomisiones_otras                   : num  1099 603 2829 2494 3691 ...
 $ cforex                              : int  0 1 0 0 0 0 0 0 1 0 ...
 $ cforex_buy                          : int  0 0 0 0 0 0 0 0 0 0 ...
 $ mforex_buy                          : num  0 0 0 0 0 0 0 0 0 0 ...
 $ cforex_sell                         : int  0 1 0 0 0 0 0 0 1 0 ...
 $ mforex_sell                         : num  0 235 0 0 0 ...
 $ ctransferencias_recibidas           : int  1 1 0 0 2 0 5 1 5 11 ...
 $ mtransferencias_recibidas           : num  3120 87918 0 0 54235 ...
 $ ctransferencias_emitidas            : int  3 4 0 0 5 2 14 1 3 2 ...
 $ mtransferencias_emitidas            : num  26979 10088 0 0 154660 ...
 $ cextraccion_autoservicio            : int  0 1 0 0 3 9 4 0 3 0 ...
 $ mextraccion_autoservicio            : num  0 5865 0 0 70380 ...
 $ ccheques_depositados                : int  0 0 0 2 0 0 0 0 0 1 ...
 $ mcheques_depositados                : num  0 0 0 105570 0 ...
 $ ccheques_emitidos                   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ mcheques_emitidos                   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ ccheques_depositados_rechazados     : int  0 0 0 0 0 0 0 0 0 0 ...
 $ mcheques_depositados_rechazados     : num  0 0 0 0 0 0 0 0 0 0 ...
 $ ccheques_emitidos_rechazados        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ mcheques_emitidos_rechazados        : num  0 0 0 0 0 0 0 0 0 0 ...
 $ tcallcenter                         : int  0 0 0 0 0 0 0 0 1 0 ...
 $ ccallcenter_transacciones           : int  0 0 0 0 0 0 0 0 3 0 ...
 $ thomebanking                        : int  1 0 1 1 1 1 1 1 1 1 ...
 $ chomebanking_transacciones          : int  4 4 6 21 96 69 52 150 126 34 ...
 $ ccajas_transacciones                : int  0 0 0 0 0 0 0 0 0 0 ...
  [list output truncated]
 - attr(*, ".internal.selfref")=<externalptr>

In [14]:
# defino los datos que forma parte del training     # En este caso defini undesampling todo el dataset.
# aqui se hace el undersampling de los CONTINUA
# notar que para esto utilizo la SEGUNDA semilla

set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")   #Lu. "L'Ecuyer-CMRG" es un tipo de generador de números aleatorios que permite reproducibilidad.
                                                                  #Esto asegura que cada vez que corras el código, los mismos registros serán seleccionados en el undersampling.
dataset_train[, azar := runif(nrow(dataset_train))]          #Lu. Genera un vector de números aleatorios uniformes entre 0 y 1, de longitud igual al número de filas del dataset.
                                                                  #Dentro de data.table crea una nueva columna llamada azar con estos valores aleatorios.
                                                                  # Estacolumna servirá para seleccionar aleatoriamente qué filas de la clase mayoritaria se mantendrán en el entrenamiento.
dataset_train[, training := 0L]                              #Lu. Crea una columna training inicializada en 0 para marcar qué filas se usarán en el entrenamiento. 0L indica entero (tipo integer).

dataset_train[
  foto_mes %in% c(202107) &
    (azar <= PARAM$trainingstrategy$undersampling | clase_ternaria %in% c("BAJA+1", "BAJA+2")),  #Lu. selecciona aleatoriamente una fracción de las filas según el parámetro undersampling
                                                                                                      # asegura que todas las filas de las clases minoritarias se mantengan, sin importar el azar
  training := 1L   # Lu. Marca estas filas como parte del conjunto de entrenamiento.
]

In [15]:
# los campos que se van a utilizar

campos_buenos <- setdiff(
  colnames(dataset_train),
  c("clase_ternaria", "clase01", "azar", "training")
)

In [16]:
# dejo los datos en el formato que necesita LightGBM

dtrain <- lgb.Dataset(
  data= data.matrix(dataset_train[training == 1L, campos_buenos, with= FALSE]),
  label= dataset_train[training == 1L, clase01],
  free_raw_data= FALSE
)

nrow(dtrain)
ncol(dtrain)

[1] 83124

[1] 154

2.2.5 Configuracion Bayesian Optimization

In [17]:
# En el argumento x llegan los parmaetros de la bayesiana
#  devuelve la AUC en cross validation del modelo entrenado

EstimarGanancia_AUC_lightgbm <- function(x) {

  # Lu. Defino max_depth en función de num_leaves                                    # Lu.
  x$max_depth <- ceiling(log2(x$num_leaves + 1))                                     # +1 es un truco para asegurar que siempre haya suficiente profundidad, evitando que el árbol intente crecer más hojas de las que caben según max_depth.


  # x pisa (o agrega) a param_fijos
  param_completo <- modifyList(PARAM$lgbm$param_fijos, x)

  # entreno LightGBM
  modelocv <- lgb.cv(
    data= dtrain,
    nfold= PARAM$hyperparametertuning$xval_folds,    # Lu. Quedó definido 5 folds. Valor confiable para la maroria de los datasets. No tiene sentido optimizarlo
    stratified= TRUE,                                # Lu. Importante porque hay clases desbalanceadas
    param= param_completo
  )

  # obtengo la ganancia
  AUC <- modelocv$best_score

  # hago espacio en la memoria
  rm(modelocv)
  gc(full= TRUE, verbose= FALSE)

  message(format(Sys.time(), "%a %b %d %X %Y"), " AUC ", AUC)

  return(AUC)
}

In [18]:
# Aqui comienza la configuracion de la Bayesian Optimization

# en este archivo quedan la evolucion binaria de la BO
kbayesiana <- "bayesiana.RDATA"

funcion_optimizar <- EstimarGanancia_AUC_lightgbm # la funcion que voy a maximizar

configureMlr(show.learner.output= FALSE)

# configuro la busqueda bayesiana,  los hiperparametros que se van a optimizar
# por favor, no desesperarse por lo complejo

obj.fun <- makeSingleObjectiveFunction(
  fn= funcion_optimizar, # la funcion que voy a maximizar
  minimize= FALSE, # estoy Maximizando la ganancia
  noisy= TRUE,
  par.set= PARAM$hypeparametertuning$hs, # definido al comienzo del programa.     Lu. Son los rangos de valores de los hiperparametros a optimizar
  has.simple.signature= FALSE # paso los parametros en una lista
)

# cada 600 segundos guardo el resultado intermedio
ctrl <- makeMBOControl(
  save.on.disk.at.time= 600, # se graba cada 600 segundos
  save.file.path= kbayesiana
) # se graba cada 600 segundos

# indico la cantidad de iteraciones que va a tener la Bayesian Optimization
ctrl <- setMBOControlTermination(
  ctrl,
  iters= PARAM$hyperparametertuning$iteraciones
) # cantidad de iteraciones

# defino el método estandar para la creacion de los puntos iniciales,
# los "No Inteligentes"
ctrl <- setMBOControlInfill(ctrl, crit= makeMBOInfillCritEI())

# establezco la funcion que busca el maximo
surr.km <- makeLearner(
  "regr.km",
  predict.type= "se",
  covtype= "matern3_2",
  control= list(trace= TRUE)
)

2.2.6 Corrida Bayesian Optimization

In [19]:
# inicio la optimizacion bayesiana, retomando si ya existe
# es la celda mas lenta de todo el notebook

if (!file.exists(kbayesiana)) {
  bayesiana_salida <- mbo(obj.fun, learner= surr.km, control= ctrl)
} else {
  bayesiana_salida <- mboContinue(kbayesiana) # retomo en caso que ya exista
}

Tue Nov 04 03:17:57 AM 2025 AUC 0.926243592870419

[mbo] 11: num_iterations=463; learning_rate=0.00546; feature_fraction=0.542; min_data_in_leaf=443; num_leaves=1022; bagging_fraction=0.868; bagging_freq=3; scale_pos_weight=16 : y = 0.926 : 87.8 secs : infill_ei

Saved the current state after iteration 12 in the file bayesiana.RDATA.

Tue Nov 04 03:24:15 AM 2025 AUC 0.930680371536239

[mbo] 12: num_iterations=2221; learning_rate=0.00756; feature_fraction=0.834; min_data_in_leaf=435; num_leaves=1023; bagging_fraction=0.943; bagging_freq=2; scale_pos_weight=15 : y = 0.931 : 378.0 secs : infill_ei

Tue Nov 04 03:28:47 AM 2025 AUC 0.929215980403803

[mbo] 13: num_iterations=1991; learning_rate=0.0109; feature_fraction=0.696; min_data_in_leaf=430; num_leaves=969; bagging_fraction=0.841; bagging_freq=5; scale_pos_weight=13 : y = 0.929 : 271.1 secs : infill_ei

Saved the current state after iteration 14 in the file bayesiana.RDATA.

Tue Nov 04 03:35:54 AM 2025 AUC 0.929825748002504

[mbo] 14: num_iterations=2710; learning_rate=0.00522; feature_fraction=0.82; min_data_in_leaf=475; num_leaves=1021; bagging_fraction=0.985; bagging_freq=3; scale_pos_weight=20 : y = 0.93 : 426.3 secs : infill_ei

Tue Nov 04 03:38:46 AM 2025 AUC 0.929805801499902

[mbo] 15: num_iterations=1310; learning_rate=0.00502; feature_fraction=0.839; min_data_in_leaf=449; num_leaves=433; bagging_fraction=0.963; bagging_freq=6; scale_pos_weight=15 : y = 0.93 : 171.7 secs : infill_ei

Tue Nov 04 03:42:53 AM 2025 AUC 0.931226904919711

[mbo] 16: num_iterations=1445; learning_rate=0.00567; feature_fraction=0.504; min_data_in_leaf=470; num_leaves=905; bagging_fraction=0.928; bagging_freq=6; scale_pos_weight=1 : y = 0.931 : 246.9 secs : infill_ei

Saved the current state after iteration 17 in the file bayesiana.RDATA.

Tue Nov 04 03:46:16 AM 2025 AUC 0.93122179308398

[mbo] 17: num_iterations=1439; learning_rate=0.0194; feature_fraction=0.508; min_data_in_leaf=380; num_leaves=832; bagging_fraction=0.919; bagging_freq=1; scale_pos_weight=4 : y = 0.931 : 201.8 secs : infill_ei

Tue Nov 04 03:51:03 AM 2025 AUC 0.931648742109484

[mbo] 18: num_iterations=2945; learning_rate=0.0106; feature_fraction=0.653; min_data_in_leaf=490; num_leaves=824; bagging_fraction=0.92; bagging_freq=1; scale_pos_weight=4 : y = 0.932 : 286.8 secs : infill_ei

Tue Nov 04 03:55:46 AM 2025 AUC 0.929509844609426

[mbo] 19: num_iterations=2741; learning_rate=0.0149; feature_fraction=0.632; min_data_in_leaf=442; num_leaves=985; bagging_fraction=1; bagging_freq=1; scale_pos_weight=5 : y = 0.93 : 282.3 secs : infill_ei

Saved the current state after iteration 20 in the file bayesiana.RDATA.

Tue Nov 04 03:59:12 AM 2025 AUC 0.930840631184917

[mbo] 20: num_iterations=1952; learning_rate=0.0112; feature_fraction=0.618; min_data_in_leaf=490; num_leaves=717; bagging_fraction=0.89; bagging_freq=1; scale_pos_weight=2 : y = 0.931 : 205.1 secs : infill_ei

Tue Nov 04 04:01:37 AM 2025 AUC 0.929598117515528

[mbo] 21: num_iterations=1553; learning_rate=0.00679; feature_fraction=0.707; min_data_in_leaf=444; num_leaves=288; bagging_fraction=0.974; bagging_freq=0; scale_pos_weight=1 : y = 0.93 : 145.1 secs : infill_ei

Tue Nov 04 04:06:28 AM 2025 AUC 0.930728000056195

[mbo] 22: num_iterations=2998; learning_rate=0.00613; feature_fraction=0.76; min_data_in_leaf=474; num_leaves=634; bagging_fraction=0.805; bagging_freq=1; scale_pos_weight=4 : y = 0.931 : 289.8 secs : infill_ei

Saved the current state after iteration 23 in the file bayesiana.RDATA.

Tue Nov 04 04:11:34 AM 2025 AUC 0.93066942243844

[mbo] 23: num_iterations=2277; learning_rate=0.00529; feature_fraction=0.538; min_data_in_leaf=500; num_leaves=778; bagging_fraction=0.878; bagging_freq=1; scale_pos_weight=4 : y = 0.931 : 306.3 secs : infill_ei

Tue Nov 04 04:19:43 AM 2025 AUC 0.930407647041077

[mbo] 24: num_iterations=2985; learning_rate=0.00954; feature_fraction=0.641; min_data_in_leaf=492; num_leaves=742; bagging_fraction=0.903; bagging_freq=2; scale_pos_weight=18 : y = 0.93 : 488.2 secs : infill_ei

Saved the current state after iteration 25 in the file bayesiana.RDATA.

Tue Nov 04 04:22:50 AM 2025 AUC 0.930069130407147

[mbo] 25: num_iterations=1038; learning_rate=0.00503; feature_fraction=0.516; min_data_in_leaf=412; num_leaves=1021; bagging_fraction=0.949; bagging_freq=7; scale_pos_weight=8 : y = 0.93 : 185.7 secs : infill_ei

Tue Nov 04 04:27:55 AM 2025 AUC 0.930705537413261

[mbo] 26: num_iterations=3000; learning_rate=0.00777; feature_fraction=0.864; min_data_in_leaf=430; num_leaves=956; bagging_fraction=0.899; bagging_freq=1; scale_pos_weight=6 : y = 0.931 : 304.5 secs : infill_ei

Tue Nov 04 04:35:22 AM 2025 AUC 0.93004227156249

[mbo] 27: num_iterations=2951; learning_rate=0.0119; feature_fraction=0.723; min_data_in_leaf=496; num_leaves=334; bagging_fraction=0.921; bagging_freq=2; scale_pos_weight=7 : y = 0.93 : 447.0 secs : infill_ei

Saved the current state after iteration 28 in the file bayesiana.RDATA.

Tue Nov 04 04:40:10 AM 2025 AUC 0.92928376772686

[mbo] 28: num_iterations=2999; learning_rate=0.00693; feature_fraction=0.755; min_data_in_leaf=500; num_leaves=807; bagging_fraction=0.942; bagging_freq=1; scale_pos_weight=6 : y = 0.929 : 287.2 secs : infill_ei

Tue Nov 04 04:48:14 AM 2025 AUC 0.931693882205661

[mbo] 29: num_iterations=2991; learning_rate=0.0133; feature_fraction=0.708; min_data_in_leaf=415; num_leaves=923; bagging_fraction=0.906; bagging_freq=2; scale_pos_weight=2 : y = 0.932 : 483.1 secs : infill_ei

Saved the current state after iteration 30 in the file bayesiana.RDATA.

Tue Nov 04 04:56:01 AM 2025 AUC 0.93130112687912

[mbo] 30: num_iterations=2857; learning_rate=0.0117; feature_fraction=0.659; min_data_in_leaf=364; num_leaves=960; bagging_fraction=0.884; bagging_freq=2; scale_pos_weight=4 : y = 0.931 : 466.2 secs : infill_ei

Tue Nov 04 05:02:47 AM 2025 AUC 0.931168861942263

[mbo] 31: num_iterations=2977; learning_rate=0.0119; feature_fraction=0.687; min_data_in_leaf=481; num_leaves=940; bagging_fraction=0.858; bagging_freq=4; scale_pos_weight=1 : y = 0.931 : 405.3 secs : infill_ei

Saved the current state after iteration 32 in the file bayesiana.RDATA.

Tue Nov 04 05:07:01 AM 2025 AUC 0.930073053019545

[mbo] 32: num_iterations=1442; learning_rate=0.00949; feature_fraction=0.515; min_data_in_leaf=338; num_leaves=952; bagging_fraction=0.904; bagging_freq=4; scale_pos_weight=6 : y = 0.93 : 253.7 secs : infill_ei

Tue Nov 04 05:10:28 AM 2025 AUC 0.929683480686921

[mbo] 33: num_iterations=2114; learning_rate=0.015; feature_fraction=0.678; min_data_in_leaf=429; num_leaves=798; bagging_fraction=0.828; bagging_freq=0; scale_pos_weight=4 : y = 0.93 : 206.6 secs : infill_ei

Tue Nov 04 05:16:02 AM 2025 AUC 0.930302520055382

[mbo] 34: num_iterations=2908; learning_rate=0.0133; feature_fraction=0.594; min_data_in_leaf=472; num_leaves=741; bagging_fraction=0.882; bagging_freq=1; scale_pos_weight=2 : y = 0.93 : 332.7 secs : infill_ei

Saved the current state after iteration 35 in the file bayesiana.RDATA.

Tue Nov 04 05:21:38 AM 2025 AUC 0.930935717099977

[mbo] 35: num_iterations=2225; learning_rate=0.00607; feature_fraction=0.669; min_data_in_leaf=481; num_leaves=787; bagging_fraction=0.804; bagging_freq=2; scale_pos_weight=2 : y = 0.931 : 335.5 secs : infill_ei

Tue Nov 04 05:26:57 AM 2025 AUC 0.930691398049409

[mbo] 36: num_iterations=2135; learning_rate=0.00892; feature_fraction=0.818; min_data_in_leaf=412; num_leaves=873; bagging_fraction=0.839; bagging_freq=3; scale_pos_weight=3 : y = 0.931 : 318.8 secs : infill_ei

Saved the current state after iteration 37 in the file bayesiana.RDATA.

Tue Nov 04 05:35:00 AM 2025 AUC 0.930043623472399

[mbo] 37: num_iterations=2979; learning_rate=0.0103; feature_fraction=0.679; min_data_in_leaf=448; num_leaves=935; bagging_fraction=0.886; bagging_freq=2; scale_pos_weight=1 : y = 0.93 : 481.8 secs : infill_ei

Tue Nov 04 05:40:52 AM 2025 AUC 0.929717756621701

[mbo] 38: num_iterations=2580; learning_rate=0.00829; feature_fraction=0.69; min_data_in_leaf=443; num_leaves=975; bagging_fraction=0.9; bagging_freq=6; scale_pos_weight=5 : y = 0.93 : 351.4 secs : infill_ei

Saved the current state after iteration 39 in the file bayesiana.RDATA.

Tue Nov 04 05:45:37 AM 2025 AUC 0.930733675351577

[mbo] 39: num_iterations=2643; learning_rate=0.0139; feature_fraction=0.627; min_data_in_leaf=323; num_leaves=983; bagging_fraction=0.913; bagging_freq=1; scale_pos_weight=6 : y = 0.931 : 284.9 secs : infill_ei

Tue Nov 04 05:50:06 AM 2025 AUC 0.931650982365998

[mbo] 40: num_iterations=1474; learning_rate=0.0128; feature_fraction=0.501; min_data_in_leaf=463; num_leaves=959; bagging_fraction=0.969; bagging_freq=4; scale_pos_weight=7 : y = 0.932 : 268.6 secs : infill_ei

Tue Nov 04 05:58:26 AM 2025 AUC 0.930005179602218

[mbo] 41: num_iterations=3000; learning_rate=0.0133; feature_fraction=0.737; min_data_in_leaf=392; num_leaves=866; bagging_fraction=0.891; bagging_freq=2; scale_pos_weight=3 : y = 0.93 : 498.5 secs : infill_ei

Saved the current state after iteration 42 in the file bayesiana.RDATA.

Tue Nov 04 06:05:30 AM 2025 AUC 0.931337393311001

[mbo] 42: num_iterations=2913; learning_rate=0.0107; feature_fraction=0.65; min_data_in_leaf=405; num_leaves=431; bagging_fraction=0.773; bagging_freq=2; scale_pos_weight=2 : y = 0.931 : 423.2 secs : infill_ei

Tue Nov 04 06:10:20 AM 2025 AUC 0.93132640876626

[mbo] 43: num_iterations=1965; learning_rate=0.017; feature_fraction=0.506; min_data_in_leaf=489; num_leaves=1024; bagging_fraction=0.848; bagging_freq=1; scale_pos_weight=6 : y = 0.931 : 289.6 secs : infill_ei

Saved the current state after iteration 44 in the file bayesiana.RDATA.

Tue Nov 04 06:16:40 AM 2025 AUC 0.931189648509558

[mbo] 44: num_iterations=1876; learning_rate=0.00651; feature_fraction=0.5; min_data_in_leaf=438; num_leaves=830; bagging_fraction=0.959; bagging_freq=2; scale_pos_weight=5 : y = 0.931 : 378.3 secs : infill_ei

Tue Nov 04 06:23:46 AM 2025 AUC 0.930637330940895

[mbo] 45: num_iterations=2950; learning_rate=0.00931; feature_fraction=0.649; min_data_in_leaf=416; num_leaves=775; bagging_fraction=0.805; bagging_freq=3; scale_pos_weight=3 : y = 0.931 : 425.6 secs : infill_ei

Saved the current state after iteration 46 in the file bayesiana.RDATA.

Tue Nov 04 06:29:25 AM 2025 AUC 0.929926690465692

[mbo] 46: num_iterations=2964; learning_rate=0.012; feature_fraction=0.654; min_data_in_leaf=500; num_leaves=441; bagging_fraction=0.703; bagging_freq=4; scale_pos_weight=3 : y = 0.93 : 339.0 secs : infill_ei

Tue Nov 04 06:34:52 AM 2025 AUC 0.931200524507651

[mbo] 47: num_iterations=2570; learning_rate=0.0116; feature_fraction=0.57; min_data_in_leaf=365; num_leaves=882; bagging_fraction=0.812; bagging_freq=1; scale_pos_weight=2 : y = 0.931 : 326.1 secs : infill_ei

Saved the current state after iteration 48 in the file bayesiana.RDATA.

Tue Nov 04 06:40:43 AM 2025 AUC 0.930821220667843

[mbo] 48: num_iterations=2779; learning_rate=0.0144; feature_fraction=0.709; min_data_in_leaf=432; num_leaves=916; bagging_fraction=0.788; bagging_freq=5; scale_pos_weight=1 : y = 0.931 : 350.4 secs : infill_ei

Tue Nov 04 06:43:48 AM 2025 AUC 0.930637991703437

[mbo] 49: num_iterations=1334; learning_rate=0.00717; feature_fraction=0.502; min_data_in_leaf=462; num_leaves=1008; bagging_fraction=0.937; bagging_freq=1; scale_pos_weight=5 : y = 0.931 : 183.4 secs : infill_ei

Tue Nov 04 06:50:48 AM 2025 AUC 0.930452268081238

[mbo] 50: num_iterations=2433; learning_rate=0.00725; feature_fraction=0.603; min_data_in_leaf=258; num_leaves=870; bagging_fraction=0.854; bagging_freq=2; scale_pos_weight=2 : y = 0.93 : 420.0 secs : infill_ei

Saved the current state after iteration 51 in the file bayesiana.RDATA.

Tue Nov 04 06:54:49 AM 2025 AUC 0.930906548732065

[mbo] 51: num_iterations=2510; learning_rate=0.00995; feature_fraction=0.653; min_data_in_leaf=433; num_leaves=557; bagging_fraction=0.896; bagging_freq=1; scale_pos_weight=4 : y = 0.931 : 240.1 secs : infill_ei

Tue Nov 04 06:57:33 AM 2025 AUC 0.9316534165878

[mbo] 52: num_iterations=1764; learning_rate=0.0123; feature_fraction=0.651; min_data_in_leaf=500; num_leaves=899; bagging_fraction=0.724; bagging_freq=1; scale_pos_weight=2 : y = 0.932 : 162.5 secs : infill_ei

Tue Nov 04 07:02:42 AM 2025 AUC 0.931310457927411

[mbo] 53: num_iterations=2074; learning_rate=0.00921; feature_fraction=0.615; min_data_in_leaf=471; num_leaves=995; bagging_fraction=0.745; bagging_freq=2; scale_pos_weight=1 : y = 0.931 : 308.4 secs : infill_ei

Saved the current state after iteration 54 in the file bayesiana.RDATA.

Tue Nov 04 07:07:43 AM 2025 AUC 0.930644037741734

[mbo] 54: num_iterations=1910; learning_rate=0.0133; feature_fraction=0.5; min_data_in_leaf=498; num_leaves=721; bagging_fraction=0.85; bagging_freq=6; scale_pos_weight=6 : y = 0.931 : 300.2 secs : infill_ei

Tue Nov 04 07:11:52 AM 2025 AUC 0.931177120018512

[mbo] 55: num_iterations=1738; learning_rate=0.0113; feature_fraction=0.56; min_data_in_leaf=415; num_leaves=1008; bagging_fraction=0.653; bagging_freq=3; scale_pos_weight=2 : y = 0.931 : 248.0 secs : infill_ei

Tue Nov 04 07:17:49 AM 2025 AUC 0.93011358090657

[mbo] 56: num_iterations=1952; learning_rate=0.0196; feature_fraction=0.543; min_data_in_leaf=451; num_leaves=967; bagging_fraction=0.885; bagging_freq=2; scale_pos_weight=1 : y = 0.93 : 357.0 secs : infill_ei

Saved the current state after iteration 57 in the file bayesiana.RDATA.

Tue Nov 04 07:24:30 AM 2025 AUC 0.931169567449137

[mbo] 57: num_iterations=2729; learning_rate=0.0114; feature_fraction=0.634; min_data_in_leaf=493; num_leaves=956; bagging_fraction=0.738; bagging_freq=2; scale_pos_weight=2 : y = 0.931 : 400.1 secs : infill_ei

Tue Nov 04 07:28:12 AM 2025 AUC 0.930510238518392

[mbo] 58: num_iterations=2168; learning_rate=0.012; feature_fraction=0.617; min_data_in_leaf=401; num_leaves=868; bagging_fraction=0.713; bagging_freq=1; scale_pos_weight=2 : y = 0.931 : 221.2 secs : infill_ei

Saved the current state after iteration 59 in the file bayesiana.RDATA.

Tue Nov 04 07:31:23 AM 2025 AUC 0.929943319070941

[mbo] 59: num_iterations=1367; learning_rate=0.0124; feature_fraction=0.822; min_data_in_leaf=345; num_leaves=1008; bagging_fraction=0.831; bagging_freq=4; scale_pos_weight=2 : y = 0.93 : 189.4 secs : infill_ei

Tue Nov 04 07:39:11 AM 2025 AUC 0.931502828846851

[mbo] 60: num_iterations=2990; learning_rate=0.0133; feature_fraction=0.706; min_data_in_leaf=349; num_leaves=659; bagging_fraction=0.834; bagging_freq=2; scale_pos_weight=2 : y = 0.932 : 468.2 secs : infill_ei

Saved the current state after iteration 61 in the file bayesiana.RDATA.

Tue Nov 04 07:42:32 AM 2025 AUC 0.930644961431181

[mbo] 61: num_iterations=2128; learning_rate=0.0138; feature_fraction=0.838; min_data_in_leaf=484; num_leaves=905; bagging_fraction=0.771; bagging_freq=1; scale_pos_weight=1 : y = 0.931 : 199.9 secs : infill_ei

Tue Nov 04 07:46:45 AM 2025 AUC 0.929563196901312

[mbo] 62: num_iterations=2808; learning_rate=0.014; feature_fraction=0.716; min_data_in_leaf=416; num_leaves=368; bagging_fraction=0.868; bagging_freq=0; scale_pos_weight=3 : y = 0.93 : 251.9 secs : infill_ei

Tue Nov 04 07:55:48 AM 2025 AUC 0.930193416250706

[mbo] 63: num_iterations=2721; learning_rate=0.00833; feature_fraction=0.529; min_data_in_leaf=342; num_leaves=675; bagging_fraction=0.979; bagging_freq=2; scale_pos_weight=4 : y = 0.93 : 542.6 secs : infill_ei

Saved the current state after iteration 64 in the file bayesiana.RDATA.

Tue Nov 04 08:01:58 AM 2025 AUC 0.930842095943697

[mbo] 64: num_iterations=2856; learning_rate=0.013; feature_fraction=0.706; min_data_in_leaf=500; num_leaves=910; bagging_fraction=0.748; bagging_freq=3; scale_pos_weight=3 : y = 0.931 : 369.1 secs : infill_ei

Tue Nov 04 08:09:39 AM 2025 AUC 0.93120404120109

[mbo] 65: num_iterations=2814; learning_rate=0.00843; feature_fraction=0.568; min_data_in_leaf=410; num_leaves=985; bagging_fraction=0.915; bagging_freq=5; scale_pos_weight=2 : y = 0.931 : 460.3 secs : infill_ei

Saved the current state after iteration 66 in the file bayesiana.RDATA.

Tue Nov 04 08:16:08 AM 2025 AUC 0.930605953807553

[mbo] 66: num_iterations=2539; learning_rate=0.00996; feature_fraction=0.65; min_data_in_leaf=345; num_leaves=340; bagging_fraction=0.877; bagging_freq=2; scale_pos_weight=2 : y = 0.931 : 387.3 secs : infill_ei

Tue Nov 04 08:21:47 AM 2025 AUC 0.930764885516014

[mbo] 67: num_iterations=2314; learning_rate=0.00783; feature_fraction=0.568; min_data_in_leaf=500; num_leaves=1000; bagging_fraction=0.762; bagging_freq=4; scale_pos_weight=3 : y = 0.931 : 337.9 secs : infill_ei

Saved the current state after iteration 68 in the file bayesiana.RDATA.

Tue Nov 04 08:24:47 AM 2025 AUC 0.930835940790419

[mbo] 68: num_iterations=1882; learning_rate=0.00589; feature_fraction=0.646; min_data_in_leaf=498; num_leaves=907; bagging_fraction=0.78; bagging_freq=1; scale_pos_weight=4 : y = 0.931 : 179.3 secs : infill_ei

Tue Nov 04 08:28:31 AM 2025 AUC 0.931320918078479

[mbo] 69: num_iterations=1707; learning_rate=0.0102; feature_fraction=0.72; min_data_in_leaf=499; num_leaves=960; bagging_fraction=0.87; bagging_freq=5; scale_pos_weight=1 : y = 0.931 : 223.8 secs : infill_ei

Tue Nov 04 08:32:09 AM 2025 AUC 0.931614156882615

[mbo] 70: num_iterations=1502; learning_rate=0.0137; feature_fraction=0.711; min_data_in_leaf=417; num_leaves=562; bagging_fraction=0.873; bagging_freq=3; scale_pos_weight=1 : y = 0.932 : 216.8 secs : infill_ei

Saved the current state after iteration 71 in the file bayesiana.RDATA.

Tue Nov 04 08:32:56 AM 2025 AUC 0.928725516448929

[mbo] 71: num_iterations=303; learning_rate=0.0133; feature_fraction=0.71; min_data_in_leaf=452; num_leaves=818; bagging_fraction=0.846; bagging_freq=3; scale_pos_weight=1 : y = 0.929 : 46.0 secs : infill_ei

Tue Nov 04 08:37:56 AM 2025 AUC 0.931098351991661

[mbo] 72: num_iterations=1846; learning_rate=0.00699; feature_fraction=0.601; min_data_in_leaf=416; num_leaves=742; bagging_fraction=0.908; bagging_freq=3; scale_pos_weight=1 : y = 0.931 : 299.2 secs : infill_ei

Tue Nov 04 08:42:03 AM 2025 AUC 0.931296938901963

[mbo] 73: num_iterations=1544; learning_rate=0.0189; feature_fraction=0.676; min_data_in_leaf=414; num_leaves=819; bagging_fraction=0.876; bagging_freq=2; scale_pos_weight=1 : y = 0.931 : 246.3 secs : infill_ei

Tue Nov 04 08:46:17 AM 2025 AUC 0.930237826925395

[mbo] 74: num_iterations=1700; learning_rate=0.0144; feature_fraction=0.659; min_data_in_leaf=493; num_leaves=589; bagging_fraction=0.795; bagging_freq=2; scale_pos_weight=2 : y = 0.93 : 253.7 secs : infill_ei

Saved the current state after iteration 75 in the file bayesiana.RDATA.

Tue Nov 04 08:49:56 AM 2025 AUC 0.929959774070706

[mbo] 75: num_iterations=1489; learning_rate=0.0129; feature_fraction=0.723; min_data_in_leaf=409; num_leaves=894; bagging_fraction=0.926; bagging_freq=4; scale_pos_weight=1 : y = 0.93 : 217.9 secs : infill_ei

Tue Nov 04 08:56:10 AM 2025 AUC 0.931370367727483

[mbo] 76: num_iterations=2177; learning_rate=0.00542; feature_fraction=0.537; min_data_in_leaf=420; num_leaves=522; bagging_fraction=0.772; bagging_freq=2; scale_pos_weight=2 : y = 0.931 : 373.1 secs : infill_ei

Tue Nov 04 09:03:03 AM 2025 AUC 0.93048030919451

[mbo] 77: num_iterations=2548; learning_rate=0.0167; feature_fraction=0.703; min_data_in_leaf=401; num_leaves=604; bagging_fraction=0.925; bagging_freq=2; scale_pos_weight=1 : y = 0.93 : 412.6 secs : infill_ei

Saved the current state after iteration 78 in the file bayesiana.RDATA.

Tue Nov 04 09:06:31 AM 2025 AUC 0.930521543289665

[mbo] 78: num_iterations=1190; learning_rate=0.00732; feature_fraction=0.534; min_data_in_leaf=443; num_leaves=574; bagging_fraction=0.874; bagging_freq=3; scale_pos_weight=6 : y = 0.931 : 206.3 secs : infill_ei

Tue Nov 04 09:13:53 AM 2025 AUC 0.930778958821682


In [ ]:

tb_bayesiana <- as.data.table(bayesiana_salida$opt.path)
colnames( tb_bayesiana)

 [1] "num_iterations"   "learning_rate"    "feature_fraction" "min_data_in_leaf"
 [5] "num_leaves"       "bagging_fraction" "bagging_freq"     "scale_pos_weight"
 [9] "y"                "dob"              "eol"              "error.message"
[13] "exec.time"        "ei"               "error.model"      "train.time"
[17] "prop.type"        "propose.time"     "se"               "mean"

In [ ]:
# almaceno los resultados de la Bayesian Optimization
# y capturo los mejores hiperparametros encontrados

tb_bayesiana <- as.data.table(bayesiana_salida$opt.path)

tb_bayesiana[, iter := .I]

# ordeno en forma descendente por AUC = y
setorder(tb_bayesiana, -y)

# grabo para eventualmente poder utilizarlos en OTRA corrida
fwrite( tb_bayesiana,
  file= "BO_log.txt",
  sep= "\t"
)

# los mejores hiperparámetros son los que quedaron en el registro 1 de la tabla
PARAM$out$lgbm$mejores_hiperparametros <- tb_bayesiana[
  1, # el primero es el de mejor AUC
  setdiff(colnames(tb_bayesiana),
    c("y","dob","eol","error.message","exec.time","ei","error.model",
      "train.time","prop.type","propose.time","se","mean","iter")),
  with= FALSE
]


PARAM$out$lgbm$y <- tb_bayesiana[1, y]

In [ ]:
write_yaml( PARAM, file="PARAM.yml")

In [ ]:
print(PARAM$out$lgbm$mejores_hiperparametros)
print(PARAM$out$lgbm$y)

   num_iterations learning_rate feature_fraction min_data_in_leaf num_leaves
            <int>         <num>            <num>            <int>      <int>
1:            585    0.01156296        0.5956823              268        432
   bagging_fraction bagging_freq scale_pos_weight
              <num>        <int>            <int>
1:        0.8326237            1               10
[1] 0.9318529

## 2.3  Produccion

### Final Training
Construyo el modelo final, que es uno solo, no hace ningun tipo de particion < training, validation, testing>]

In [ ]:
setwd("/content/buckets/b1/exp")
experimento <- paste0("exp", PARAM$experimento)
dir.create(experimento, showWarnings= FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento ))

#### Final Training Dataset

Aqui esta la gran decision de en qué meses hago el Final Training
<br> debo utilizar los mejores hiperparámetros que encontré en la optimización bayesiana

In [ ]:
# clase01
dataset[, clase01 := ifelse(clase_ternaria %in% c("BAJA+1", "BAJA+2"), 1L, 0L)]

In [ ]:
dataset_train <- dataset[foto_mes %in% c(202107)]

In [ ]:
# dejo los datos en el formato que necesita LightGBM

dtrain <- lgb.Dataset(
  data= data.matrix(dataset_train[, campos_buenos, with= FALSE]),
  label= dataset_train[, clase01]
)

#### Final Training Hyperparameters

In [ ]:
param_final <- modifyList(PARAM$lgbm$param_fijos,
  PARAM$out$lgbm$mejores_hiperparametros)

param_final

$boosting
[1] "gbdt"

$objective
[1] "binary"

$metric
[1] "auc"

$first_metric_only
[1] FALSE

$boost_from_average
[1] TRUE

$feature_pre_filter
[1] FALSE

$force_row_wise
[1] TRUE

$verbosity
[1] -100

$seed
[1] 120539

$max_depth
[1] -1

$min_gain_to_split
[1] 0

$min_sum_hessian_in_leaf
[1] 0.001

$lambda_l1
[1] 0

$lambda_l2
[1] 0

$max_bin
[1] 31

$bagging_fraction
[1] 0.8326237

$bagging_freq
[1] 1

$pos_bagging_fraction
[1] 1

$neg_bagging_fraction
[1] 1

$is_unbalance
[1] FALSE

$scale_pos_weight
[1] 10

$drop_rate
[1] 0.1

$max_drop
[1] 50

$skip_drop
[1] 0.5

$extra_trees
[1] FALSE

$num_iterations
[1] 585

$learning_rate
[1] 0.01156296

$feature_fraction
[1] 0.5956823

$num_leaves
[1] 432

$min_data_in_leaf
[1] 268

#### Training
Genero el modelo final, siempre sobre TODOS los datos de  final_train, sin hacer ningun tipo de undersampling de la clase mayoritaria

In [ ]:
# este punto es muy SUTIL  y será revisado en la Clase 05

param_normalizado <- copy(param_final)
param_normalizado$min_data_in_leaf <-  round(param_final$min_data_in_leaf / PARAM$trainingstrategy$undersampling)

In [ ]:
  # entreno LightGBM

  modelo_final <- lgb.train(
    data= dtrain,
    param= param_normalizado
  )

In [ ]:
# ahora imprimo la importancia de variables

tb_importancia <- as.data.table(lgb.importance(modelo_final))
archivo_importancia <- "impo.txt"

fwrite(tb_importancia,
  file= archivo_importancia,
  sep= "\t"
)

In [ ]:
# grabo a disco el modelo en un formato para seres humanos ... ponele ...

lgb.save(modelo_final, "modelo.txt" )

### Scoring

Aplico el modelo final a los datos del futuro

In [ ]:
# aplico el modelo a los datos sin clase
dfuture <- dataset[foto_mes == 202109]

# aplico el modelo a los datos nuevos
prediccion <- predict(
  modelo_final,
  data.matrix(dfuture[, campos_buenos, with= FALSE])
)

#### Tabla Prediccion

In [ ]:
# tabla de prediccion

tb_prediccion <- dfuture[, list(numero_de_cliente)]
tb_prediccion[, prob := prediccion ]

# grabo las probabilidad del modelo
fwrite(tb_prediccion,
  file= "prediccion.txt",
  sep= "\t"
)

Kaggle Competition Submit

In [ ]:
# genero archivos con los  "envios" mejores
# suba TODOS los archivos a Kaggle

# ordeno por probabilidad descendente
setorder(tb_prediccion, -prob)

dir.create("kaggle")

for (envios in PARAM$kaggle$cortes) {

  tb_prediccion[, Predicted := 0L] # seteo inicial a 0
  tb_prediccion[1:envios, Predicted := 1L] # marclo los primeros

  archivo_kaggle <- paste0("./kaggle/KA", PARAM$experimento, "_", envios, ".csv")

  # grabo el archivo
  fwrite(tb_prediccion[, list(numero_de_cliente, Predicted)],
    file= archivo_kaggle,
    sep= ","
  )

  # subida a Kaggle, armo la linea de comando
  comando <- "kaggle competitions submit"
  competencia <- paste("-c", PARAM$kaggle$competencia)
  arch <- paste( "-f", archivo_kaggle)

  mensaje <- paste0("-m 'envios=", envios,
  "  semilla=", PARAM$semilla_primigenia,
    "'" )

  linea <- paste( comando, competencia, arch, mensaje)

  salida <- system(linea, intern=TRUE) # el submit a Kaggle
  cat(salida, "\n")
  Sys.sleep(45)
}

Successfully submitted to LaboI 2025 virtual analista sr
Successfully submitted to LaboI 2025 virtual analista sr
Successfully submitted to LaboI 2025 virtual analista sr
Successfully submitted to LaboI 2025 virtual analista sr
Successfully submitted to LaboI 2025 virtual analista sr

In [ ]:
write_yaml( PARAM, file="PARAM.yml")

In [ ]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Mon Nov 03 05:57:50 PM 2025"

Finalmente usted deberá cargar el resultado de su corrida en la Google Sheet Colaborativa,  hoja **TareaHogar-05**
<br> Siéntase libre de agregar las columnas que hagan falta a la planilla

Seguramente usted realice varias corridas de este script con distintos conjuntos de hiperparámetros, siempre cambiandole el nombre al script  y también cambiando el nombre del experimento,  deberá TODAS esas corridas en distintas lineas de la  Google Sheet Colaborativa, hoja **TareaHogar-05**

Siéntase libre de agregar columnas a la hoja **TareaHogar-05**  en caso de ser necesario.